<ol class="breadcrumb hide-phone p-0 m-0">
    <?php
    // iterate through the pages
    foreach ($this->pages as $key => $page):
        ?>
        <li>
            <?php
            // if this isn't the last page, add a link and the separator
            if ($key < count($this->pages) - 1):
                ?>
                <a href="<?php echo $page->getHref(); ?>"><?php echo __($page->getLabel()); ?></a>
                
            <?php // otherwise, just output the name
            else:
            ?>
                <?php echo __($page->getLabel()); ?>
            <?php endif; ?>
        </li>
        <?php endforeach; ?>
</ol>