<?php $this->headTitle(__('blog'))?>

            <!--container starts-->
            <div class="container">
            	<!--primary starts-->
            	<section id="primary" class="content-full-width">




                  <?php foreach($paginator as $row): ?>

                      <div class="row has-margin-bottom">
                          <?php if(!empty($row->picture)):?>
                          <div class="col-md-4 col-sm-4">

                              <img class="img-responsive center-block" src="<?php echo resizeImage($row->picture, 262, 175, $this->basePath());?>" alt="bulletin blog">

                          </div>
                          <?php endif; ?>
                          <div class="col-md-8 col-sm-8 bulletin">
                              <h4 class="media-heading"><?php echo $row->title; ?> </h4>
                              <p>on <?php echo date('d/M/Y',$row->date)?>  </p>
                              <p> <?php echo limitLength(strip_tags($row->content),200) ?></p>
                              <a class="btn btn-primary" href="<?php echo $this->url('news-entry',array('id'=>$row->newsflash_id));?>" role="button"><?= __('Read More') ?> →</a> </div>
                      </div>






                   <?php endforeach; ?> 
                    
                    
                                  <?php
 // add at the end of the file after the table
 echo $this->paginationControl(
     // the paginator object
     $this->paginator,
     // the scrolling style
     'sliding',
     // the partial to use to render the control
     array('partial/paginator.phtml', 'Application'),
     // the route to link to when a user clicks a control link
     array(
         'route' => 'news',
     )
 );
 ?>
                </section>
                <!--primary ends-->
                
                
            </div>
            <!--container ends-->
       
        
       