<div class="row">
    <div >
        <div class="box">

            <div class="box-body">
                <?php
                $form->prepare();
                $form->setAttribute('action', $this->url('admin/default',array('controller'=>'survey','action'=>$action,'id'=>$id)));
                $form->setAttribute('method', 'post');
                $form->setAttribute('role', 'form');
                $form->setAttribute('class', 'form-horizontal');

                echo $this->form()->openTag($form);
                ?>




                <div class="form-group">
                    <?php     echo $this->formLabel($form->get('name'));

                    ?>
                    <?php     echo $this->formElement($form->get('name'));

                    ?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('name'));?></p>

                </div>
                <div class="form-group">
                    <?php     echo $this->formLabel($form->get('description'));

                    ?>
                    <?php     echo $this->formElement($form->get('description'));

                    ?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('description'));?></p>

                </div>


                <div class="form-group">
                    <?php     echo $this->formLabel($form->get('status'));

                    ?>
                    <?php     echo $this->formElement($form->get('status'));

                    ?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('status'));?></p>

                </div>

                <div class="form-group">
                    <?php     echo $this->formLabel($form->get('private'));

                    ?>
                    <?php     echo $this->formElement($form->get('private'));

                    ?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('private'));?></p>

                    <p class="help-block"><?= __('private-survey-msg') ?></p>
                </div>




                <div class="form-footer">
                    <button type="submit" class="btn btn-primary"><?=__('save-changes')?></button>
                </div>
                <?php echo $this->form()->closeTag($form);  ?>
            </div>
        </div><!--end .box -->
    </div><!--end .col-lg-12 -->
</div>
<?php $this->headScript()->prependFile($this->basePath() . '/ckeditor/ckeditor.js')
?>
<script type="text/javascript">

    CKEDITOR.replace('description', {
        filebrowserBrowseUrl: '<?php echo $this->basepath() ?>/admin/filemanager',
        filebrowserImageBrowseUrl: '<?php echo $this->basepath() ?>/admin/filemanager',
        filebrowserFlashBrowseUrl: '<?php echo $this->basepath() ?>/admin/filemanager'
    });

</script> 
		