<?php
$children = $this->viewModel()->getCurrent()->getChildren();
foreach($children as $action) {
    if ($action->captureTo() == 'content') {
        break;
    }


}
$basePath = $this->basePath().'/templates/3';
?><?php
$user = null;
//$this->plugin('translate')->setTranslator(new \Zend\I18n\Translator\Translator());
$this->headTitle()
    ->setSeparator(' - ')
    ->setAutoEscape(false);


echo $this->doctype();
?>
<html <?=langMeta()?>>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo $this->headMeta()  ?>
    <meta name="description" content="<?php echo $this->getSetting('general_homepage_meta_desc') ?>"/>
    <meta name="author" content="<?php echo $this->getSetting('general_site_name') ?>"/>

    <?php echo $this->headTitle(); ?>
    <?php $icon = $this->getSetting('image_icon'); if(!empty($icon)):?>
        <link rel="shortcut icon" href="<?php echo $this->basePath(); ?>/<?php echo $this->getSetting('image_icon'); ?>">
    <?php endif; ?>
    

    <!-- Font awesome -->
    <link href="<?php echo $basePath; ?>/assets/css/font-awesome.css" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="<?php echo $basePath; ?>/assets/css/bootstrap.css" rel="stylesheet">
    <!-- Slick slider -->
    <link rel="stylesheet" type="text/css" href="<?php echo $basePath; ?>/assets/css/slick.css">
    <!-- Fancybox slider -->
    <link rel="stylesheet" href="<?php echo $basePath; ?>/assets/css/jquery.fancybox.css" type="text/css" media="screen" />
    <!-- Theme color -->
    <link id="switcher" href="<?php echo $basePath; ?>/assets/css/theme-color/default-theme.css" rel="stylesheet">

    <!-- Main style sheet -->
    <link href="<?php echo $basePath; ?>/assets/css/style.css" rel="stylesheet">


    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,400italic,300,300italic,500,700' rel='stylesheet' type='text/css'>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style>
        <?php $color=$this->getTemplateOption('footer_bgcolor'); if(!empty($color)):?>
        #mu-footer .mu-footer-top, #mu-footer .mu-footer-bottom{
            background-color: #<?php echo $color?>;
        }

        <?php endif; ?>

        <?php $color=$this->getTemplateOption('footer_textcolor'); if(!empty($color)):?>

        #mu-footer .mu-footer-top .mu-footer-top-area .mu-footer-widget h4, #mu-footer .mu-footer-top .mu-footer-top-area .mu-footer-widget p, #mu-footer .mu-footer-top .mu-footer-top-area .mu-footer-widget ul li a, {
            color: #<?php echo $color?> !important;
        }

        <?php endif; ?>


        <?php $color=$this->getTemplateOption('navbar_bgcolor'); if(!empty($color)):?>
        #mu-menu .navbar-default{
            background-color: #<?php echo $color; ?> !important;
        }

        <?php endif; ?>

        <?php $color=$this->getTemplateOption('navbar_fontcolor'); if(!empty($color)):?>
        #mu-menu .navbar-header .navbar-brand, .navbar-default .navbar-nav > li > a{
            color: #<?php echo $color?> !important;
        }

        <?php endif; ?>

        <?php $color=$this->getTemplateOption('topbar_bgcolor'); if(!empty($color)):?>
        #mu-header{
            background-color: #<?php echo $color; ?> !important;
        }

        <?php endif; ?>

        <?php $color=$this->getTemplateOption('topbar_textcolor'); if(!empty($color)):?>
        #mu-header a{
            color: #<?php echo $color?> !important;
        }

        <?php endif; ?>


        <?php $color=$this->getTemplateOption('color_page_title'); if(!empty($color)):?>
        #mu-page-breadcrumb {
            background: #<?php echo $color?> !important;
        }
        <?php endif; ?>

        <?php $color=$this->getTemplateOption('color_page_title_text'); if(!empty($color)):?>
        #mu-page-breadcrumb .mu-page-breadcrumb-area h2, #mu-page-breadcrumb .mu-page-breadcrumb-area .breadcrumb li a {
            color: #<?php echo $color?> !important;
        }
        <?php endif; ?>
    </style>


    <link href="<?php  echo  $this->url('style'); ?>?base-color=01bafd&replace-color=<?php echo $this->getTemplateOption('color_primary_color')?>&file-path=<?php echo urlencode('public/templates/3/assets/css/style.css') ?>" rel="stylesheet">


    <!-- jQuery library -->
    <script src="<?php echo $basePath; ?>/assets/js/jquery.min.js"></script>
    <?php echo $this->getSetting('general_header_scripts');?>



    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle(); ?>
    <!-- Scripts -->
    <?php echo $this->headScript() ?>


    <?php
    include('module/Application/view/layout/includes/site_header.phtml');
    ?>

</head>
<body>

<!--START SCROLL TOP BUTTON -->
<a class="scrollToTop" href="#">
    <i class="fa fa-angle-up"></i>
</a>
<!-- END SCROLL TOP BUTTON -->

<!-- Start header  -->
<header id="mu-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="mu-header-area">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                            <div class="mu-header-top-left">
                                <div class="mu-top-email">
                                    <?php if(!$this->loggedIn()):?>

                                        <a href="<?php echo $this->url('application/signin')?>"><i class="fa fa-sign-in"></i>
                                            <span><?= __('Login') ?></span></a>
                                        &nbsp; &nbsp;  | &nbsp; &nbsp;
                                        <a href="<?php echo $this->url('application/register')?>"><i class="fa fa-user-plus"></i>
                                            <span><?= __('Register') ?></span></a>


                                    <?php else: ?>
                                        <a href="<?php echo $this->url('application/dashboard')?>"><i class="fa fa-user"></i>
                                            <span><?= __('Student Portal') ?></span></a>
                                        &nbsp; &nbsp;  | &nbsp; &nbsp;
                                        <a href="<?php echo $this->url('application/logout')?>"><i class="fa fa-sign-out "></i> <span><?= __('Logout') ?></span></a>

                                    <?php endif; ?>
                                </div>

                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                            <div class="mu-header-top-right">
                                <nav>
                                    <ul class="mu-top-social-nav">
                                        <?php if(count(currencies())>1):?>
                                            <li class="dropdown user ">
                                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                                    <?=currentCurrency()->country->currency_code?>   <?php if(!empty(currentCurrency()->country->symbol_left)):?>(<?=currentCurrency()->country->symbol_left?>)<?php endif; ?> <span class="caret"></span>
                                                </a>
                                                <ul class="dropdown-menu" role="menu">
                                                    <?php foreach(currencies() as $currency):?>
                                                        <li > <a href="<?php echo $this->url('change-currency',['id'=>$currency->currency_id])?>"> <?=$currency->country->currency_code?> <?php if(!empty($currency->country->symbol_left)):?>(<?=$currency->country->symbol_left?>)<?php endif; ?> </a>  </li>
                                                    <?php endforeach; ?>
                                                </ul>
                                            </li>
                                        <?php endif; ?>
                                        <?php if(getCart()->hasItems()):?>
                                            <li class="user ">
                                                <a href="<?=$this->url('cart')?>" >
                                                    <i class="fa fa-cart-plus"></i> <?=getCart()->getTotalItems()?>
                                                </a>

                                            </li>

                                        <?php endif; ?>
                                    </ul>



                                    <ul class="mu-top-social-nav">


                                        <?php $facebook = $this->getTemplateOption('footer_facebook');?>
                                        <?php if($facebook):?>
                                            <li><a   href="<?php echo $facebook ?>"><span class="fa fa-facebook"></span></a></li>
                                        <?php endif; ?>
                                        <?php $twitter = $this->getTemplateOption('footer_twitter');?>
                                        <?php if($twitter):?>
                                            <li><a   href="<?php echo $twitter ?>"><span class="fa fa-twitter"></span></a></li>
                                        <?php endif; ?>
                                        <?php $youtube = $this->getTemplateOption('footer_youtube');?>
                                        <?php if($youtube):?>
                                            <li><a   href="<?php echo $youtube ?>"><span class="fa fa-youtube"></span></a></li>
                                        <?php endif; ?>

                                        <?php $linkedin = $this->getTemplateOption('footer_linkedin');?>
                                        <?php if($linkedin):?>
                                            <li><a   href="<?php echo $linkedin ?>"><span class="fa fa-linkedin"></span></a></li>
                                        <?php endif; ?>

                                        <?php $instagram = $this->getTemplateOption('footer_instagram');?>
                                        <?php if($instagram):?>
                                            <li><a  href="<?php echo $instagram ?>"><span class="fa fa-instagram"></span></a></li>
                                        <?php endif; ?>


                                    </ul>



                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- End header  -->
<!-- Start menu -->
<section id="mu-menu">
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <!-- FOR MOBILE VIEW COLLAPSED BUTTON -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only"><?= __('Toggle navigation') ?></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- LOGO -->
                <!-- TEXT BASED LOGO -->
                <?php $logo = $this->getSetting('image_logo'); if(empty($logo)):?>
                    <a class="navbar-brand" href="<?php echo $this->url('home');?>">
                        <span><?php echo $this->getSetting('general_site_name'); ?></span>
                    </a>
                <?php else:?>
                    <!-- IMG BASED LOGO  -->
                    <a class="navbar-brand" href="<?php echo $this->url('home');?>"><img src="<?php echo $this->basePath(); ?>/<?php echo $this->getSetting('image_logo'); ?>" alt="logo"></a>
                <?php endif; ?>

            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul id="top-menu" class="nav navbar-nav navbar-right main-nav">

                    <li ><a href="<?php echo $this->url('home');?>"><?= __('Home') ?></a></li>

                    <?php $articlesTable =  $this->getClass('Application\Model\ArticlesTable');  ?>

                    <?php foreach($articlesTable->getArticlesForParent(0,1,null,'w') as $article): ?>

                        <?php if($articlesTable->hasChildren($article->article_id,1)): ?>

                            <li class="dropdown ">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" ><?php echo $article->article_name?> <span class="fa fa-angle-down"></span></a>
                                <ul  class="dropdown-menu" role="menu">

                                    <?php foreach($articlesTable->getArticlesForParent($article->article_id,1,null,'w') as $article1): ?>
                                        <li><a href="<?php echo $this->basePath(); ?>/<?php echo $article1->alias;  ?>"><?php echo $article1->article_name?></a></li>
                                    <?php endforeach; ?>

                                </ul>
                            </li>
                        <?php else: ?>
                            <li ><a href="<?php echo $this->basePath(); ?>/<?php echo $article->alias;  ?>"><?php echo $article->article_name?></a></li>
                        <?php endif; ?>

                    <?php endforeach; ?>

                    <?php if($this->getSetting('menu_show_courses')==1):?>

                        <?php if($this->getCategories()->count()==0):?>
                            <li ><a href="<?php echo $this->url('courses'); ?>"><?php echo $this->getSetting('label_courses',__('Online Courses'))?></a></li>
                        <?php else:?>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" ><?php echo $this->getSetting('label_courses',__('Online Courses'))?> <span class="fa fa-angle-down"></span></a>
                                <ul  class="dropdown-menu" role="menu">

                                    <li ><a href="<?php echo $this->url('courses'); ?>"><?= __('All Courses') ?></a></li>

                                    <?php foreach($this->getCategories() as $category): ?>
                                        <li ><a href="<?php echo $this->url('courses') ?>?group=<?php echo $category->session_category_id ?>"><?php echo $category->category_name; ?></a></li>

                                    <?php endforeach; ?>


                                </ul>
                            </li>
                        <?php endif; ?>
                    <?php endif; ?>


                    <?php if($this->getSetting('menu_show_sessions')==1):?>
                        <li ><a href="<?php echo $this->url('sessions'); ?>"><?php echo $this->getSetting('label_sessions',__('Upcoming Sessions'))?></a></li>
                    <?php endif; ?>


                    <?php if($this->getSetting('menu_show_blog')==1):?>
                        <li ><a href="<?php echo $this->url('news'); ?>"><?php echo $this->getSetting('label_blog',__('Blog'))?></a></li>
                    <?php endif; ?>

                    <?php if($this->getSetting('menu_show_contact')==1):?>
                        <li ><a href="<?php echo $this->url('contact'); ?>"><?php echo $this->getSetting('label_contact_us',__('Contact Us'))?></a></li>
                    <?php endif; ?>
                    

                    <li><a href="#" id="mu-search-icon"><i class="fa fa-search"></i></a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
</section>
<!-- End menu -->
<!-- Start search box -->
<div id="mu-search">
    <div class="mu-search-area">
        <button class="mu-search-close"><span class="fa fa-close"></span></button>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <form class="mu-search-form" method="get" action="<?php echo $this->url('courses'); ?>">
                        <input name="filter" type="search" placeholder="<?= __('type-keywords') ?>">
                        <input type="hidden" name="sort" value=""/>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End search box -->


<?php echo $content ?>

<!-- Start footer -->
<!-- Start footer -->
<footer id="mu-footer" >
    <!-- start footer top -->
    <div class="mu-footer-top">
        <div class="container">
            <div class="mu-footer-top-area">
                <div class="row">
                    <?php if($this->getTemplateOption('show_footer_about')): ?>
                        <div class="col-lg-3 col-md-3 col-sm-3">
                            <div class="mu-footer-widget">
                                <h4><?php echo $this->getSetting('label_about_us',__('About Us'))?></h4>
                                <p><?php echo $this->getTemplateOption('footer_about_us'); ?></p>

                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="col-lg-3 col-md-3 col-sm-3">
                        <div class="mu-footer-widget">
                            <h4><?= __('Links') ?></h4>
                            <ul>
                                <?php if($this->getSetting('menu_show_courses')==1):?>
                                    <li ><a href="<?php echo $this->url('courses'); ?>"><?php echo $this->getSetting('label_courses',__('Online Courses'))?></a></li>
                                <?php endif; ?>
                                <?php if($this->getSetting('menu_show_sessions')==1):?>
                                    <li ><a href="<?php echo $this->url('sessions'); ?>"><?php echo $this->getSetting('label_sessions',__('Upcoming Sessions'))?></a></li>
                                <?php endif; ?>

                                <?php if($this->getSetting('menu_show_blog')==1):?>
                                    <li><a href="<?php echo $this->url('news'); ?>"><?php echo $this->getSetting('label_blog',__('Blog'))?></a></li>
                                <?php endif; ?>

                                <?php if($this->getSetting('menu_show_contact')==1):?>
                                    <li><a href="<?php echo $this->url('contact'); ?>"><?php echo $this->getSetting('label_contact_us',__('Contact Us'))?></a></li>
                                <?php endif; ?>

                                <li><a href="<?php echo $this->url('terms') ?>"><?= __('terms-conditions') ?></a></li>
                                <li><a href="<?php echo $this->url('privacy') ?>"><?= __('privacy-policy') ?></a></li>

                            </ul>
                        </div>
                    </div>
                    <?php if($this->getTemplateOption('show_newsletter')): ?>
                        <div class="col-lg-3 col-md-3 col-sm-3">
                            <div class="mu-footer-widget">
                                <h4><?= __('newsletter') ?></h4>
                                <p><?= __('get-updates') ?></p>

                                <?php if(!empty($this->getTemplateOption('footer_newsletter_code'))):?>
                                    <?=$this->getTemplateOption('footer_newsletter_code'); ?>
                                <?php else: ?>
                                    <form class="mu-subscribe-form">
                                        <input type="email" placeholder="<?= __('type-your-email') ?>">
                                        <button class="mu-subscribe-btn" type="submit"><?= __('subscribe') ?>!</button>
                                    </form>
                                <?php endif; ?>

                            </div>
                        </div>
                    <?php endif; ?>

                    <?php if($this->getTemplateOption('show_footer_contact')): ?>
                        <div class="col-lg-3 col-md-3 col-sm-3">
                            <div class="mu-footer-widget">
                                <h4><?php echo $this->getSetting('label_contact_us',__('Contact Us'))?></h4>
                                <address>
                                    <p><?php echo nl2br($this->getTemplateOption('footer_address')) ?></p>
                                    <?php $tel =$this->getTemplateOption('footer_tel'); if(!empty($tel)):?>
                                        <p>Phone: <?php echo $tel; ?> </p>
                                    <?php endif; ?>

                                    <?php $mail =$this->getTemplateOption('footer_email'); if(!empty($mail)):?>
                                        <p>Email: <?=$mail?></p>
                                    <?php endif; ?>
                                </address>
                            </div>
                        </div>
                    <?php endif; ?>

                </div>
            </div>
        </div>
    </div>
    <!-- end footer top -->
    <!-- start footer bottom -->
    <div class="mu-footer-bottom">
        <div class="container">
            <div class="mu-footer-bottom-area">
                <p>&copy; <?= __('all-rights-reserved') ?>. <?php echo $this->getTemplateOption('footer_credits') ?></p>
            </div>
        </div>
    </div>
    <!-- end footer bottom -->
</footer>
<!-- End footer -->
<!-- End footer -->


<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="<?php echo $basePath; ?>/assets/js/bootstrap.js"></script>
<!-- Slick slider -->
<script type="text/javascript" src="<?php echo $basePath; ?>/assets/js/slick.js"></script>
<!-- Counter -->
<script type="text/javascript" src="<?php echo $basePath; ?>/assets/js/waypoints.js"></script>
<script type="text/javascript" src="<?php echo $basePath; ?>/assets/js/jquery.counterup.js"></script>
<!-- Mixit slider -->
<script type="text/javascript" src="<?php echo $basePath; ?>/assets/js/jquery.mixitup.js"></script>
<!-- Add fancyBox -->
<script type="text/javascript" src="<?php echo $basePath; ?>/assets/js/jquery.fancybox.pack.js"></script>


<!-- Custom js -->
<script src="<?php echo $basePath; ?>/assets/js/custom.js"></script>
<?php echo $this->getSetting('general_foot_scripts');?>
</body>
</html>