<?php $this->headScript()->prependFile($this->basePath() . '/ckeditor/ckeditor.js'); ?>

<?php
$form->prepare();
$form->setAttribute('action', $this->url('admin/default',array('controller'=>'template','action'=>'customize','id'=>$id)));
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');

echo $this->form()->openTag($form);
?>
<div class="row">
    <div  style="padding-bottom: 10px">
        <button class="btn btn-primary pull-right" type="submit"><?=__('save-changes')?></button>
    </div><!--end .col-lg-12 -->
</div>

<div class="row">
    <div >



        <div class="box">
            <div class="box-head">
                <ul class="nav nav-tabs" data-toggle="tabs">
                    <?php $counter = 1?>
                    <?php foreach($groups as $group):?>

                    <li <?php if($counter==1):?> class="active" <?php endif; ?> ><a href="#<?php echo $group->group ?>" data-toggle="tab"><?php echo __(ucwords(str_replace('_',' ',$group->group))) ?></a></li>
                        <?php $counter++ ?>
                    <?php endforeach; ?>

                </ul>
            </div>

            <div class="box-body tab-content">

                <?php $counter = 1?>
                <?php foreach($groups as $group):?>
                <div class="tab-pane <?php if($counter==1):?> active  in<?php endif; ?> fade" id="<?php echo $group->group ?>">



                    <?php foreach($table->getRecordsForGroup($id,$group->group) as $row):?>

                            <div class="form-group">
                                <div class="col-sm-2">
                                    <?php     echo $this->formLabel($form->get($row->key));   ?>
                                </div>
                                <div class="col-sm-10">
                                    <?php if($row->type == 'radio'):?>
                                        <?php  echo $this->formRadio($form->get($row->key));    ?>
                                     <?php elseif($row->type=='image'): ?>

                    <div class="form-group col-sm-6" style="margin-bottom:10px">

                        <?php
                        if(!empty($row->value)){
                            $image = resizeImage($row->value,150,150,$this->basePath());
                        }
                        else{
                            $image = $no_image;
                        }

                        ?>


                        <div class="image"><img data-name="image" src="<?php echo $image ?>" alt="" id="thumb_image_<?php echo $row->template_option_id; ?>" /><br />
                            <?php echo $this->formElement($form->get($row->key)) ?>
                            <a class="pointer" onclick="image_upload('<?php echo $row->key?>', 'thumb_image_<?php echo $row->template_option_id ?>');"><?=__('browse')?></a>&nbsp;&nbsp;|&nbsp;&nbsp;<a class="pointer" onclick="$('#thumb_image_<?php echo $row->template_option_id ?>').attr('src', '<?php echo $no_image; ?>'); $('#<?php echo $row->key?>').attr('value', '');"><?=__('clear')?></a></div>
                        <div><small><?=$row->placeholder?></small></div>
                    </div>


                                    <?php else:?>
                                        <?php  echo $this->formElement($form->get($row->key));    ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                    <?php if($row->class == 'rte'):?>
                        <script type="text/javascript">

                            CKEDITOR.replace('rte_<?php echo $row->key ?>', {
                                filebrowserBrowseUrl: '<?php echo $this->basepath() ?>/admin/filemanager',
                                filebrowserImageBrowseUrl: '<?php echo $this->basepath() ?>/admin/filemanager',
                                filebrowserFlashBrowseUrl: '<?php echo $this->basepath() ?>/admin/filemanager'
                            });

                        </script>
                    <?php endif; ?>

                    <?php endforeach; ?>






                </div>
                    <?php $counter++ ?>
                <?php endforeach; ?>

            </div>

        </div>
    </div><!--end .col-lg-12 -->
</div>



<?php echo $this->form()->closeTag($form);  ?>



<script src="<?php echo $this->basePath(); ?>/static/colorpicker/jquery.colorpicker.js"></script>
<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/static/colorpicker/jquery.colorpicker.css')

;?>

<script type="text/javascript">
    $(function() {
        $('.colorpicker-full').colorpicker({
            parts:          'full',
            showOn:         'both',
            buttonColorize: true,
            showNoneButton: true,
            buttonImage : '<?php echo $this->basePath()?>/static/colorpicker/images/ui-colorpicker.png'
        });
    });
</script>

<script type="text/javascript"><!--
    function image_upload(field, thumb) {
        console.log('Field: '+field+'. Thumb:'+thumb);
        $('#dialog').remove();

        $('#content').prepend('<div id="dialog" style="padding: 3px 0px 0px 0px;"><iframe src="<?php echo $this->basePath(); ?>/admin/filemanager?&token=true&field=' + encodeURIComponent(field) + '" style="padding:0; margin: 0; display: block; width: 100%; height: 100%;" frameborder="no" scrolling="auto"></iframe></div>');

        $('#dialog').dialog({
            title: '<?=__('Image Manager')?>',
            close: function (event, ui) {
                if ($('#' + field).attr('value')) {
                    $.ajax({
                        url: '<?php echo $this->basePath(); ?>/admin/filemanager/image?&image=' + encodeURIComponent($('#' + field).val()),
                        dataType: 'text',
                        success: function(data) {

                            $('#' + thumb).replaceWith('<img src="' + data + '" alt="" id="' + thumb + '" />');
                        }
                    });
                }
                else{
                    console.log('no field content');
                }
            },
            bgiframe: false,
            width: 800,
            height: 570,
            resizable: true,
            modal: false
        });
    };
    //--></script>