<?php  $this->headTitle($pageTitle) ?>
<section class="white section">
<div class="container"  >

    <div class="row">
        <div class="col-md-12 page-header">

            <form id="filterform" class="form-inline" role="form"  method="get" action="<?php echo $this->url('courses'); ?>">
                <input type="hidden" name="group" value="<?php echo $group ?>"/>

                <div class="form-group">
                    <label class="sr-only" for="filter"><?=__('Filter')?></label>
                    <?php echo $this->formElement($text) ?>
                </div>
                <div class="form-group">
                    <label class="sr-only" for="group"><?=__('Sort')?></label>
                    <?php echo $this->formElement($sortSelect) ?>
                </div>

                <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> <?=__('Filter')?></button>
                <button type="button" onclick="$('#filterform input, #filterform select').val(''); $('#filterform').submit();" class="btn btn-inverse"><?=__('Clear')?></button>

            </form>


        </div>

    </div>

    <div class="row">
        <div class="col-md-3">

            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading"><?= __('Categories') ?></div>


                <!-- List group -->
                <ul class="list-group">
                    <li class="list-group-item"><a href="<?php echo $this->url('courses') ?>"><?=__('All Courses')?></a></li>

                    <?php foreach($categories as $category):?>
                    <li class="list-group-item"><a href="<?php echo $this->url('courses') ?>?group=<?php echo $category->session_category_id ?>"><?php echo $category->category_name; ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>



        </div>
        <div class="col-md-9">
            <?php if(!empty($description)): ?>
                    <p><?php echo $description ?></p>
            <?php endif; ?>

                <?php foreach($paginator as $row): ?>
                    <div class="row course-list" style="border-bottom:  solid 1px #cccccc; ">
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <div class="shop-item-list entry">
                                <div class="">
                                    <img src="<?php echo resizeImage($row->picture,360,252,$this->basePath()); ?>" alt="">
                                    <div class="magnifier">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-8 col-md-8" style="padding-bottom: 10px">
                            <div class="shop-list-desc">
                                <h4><a href="<?php echo $this->url('course-details',['id'=>$row->session_id,'slug'=>safeUrl($row->session_name)]);?>"><?php echo $row->session_name ?></a></h4>
                                <div class="shopmeta">
                                    <span class="pull-left">
                                        <?php if($this->getSetting('general_show_fee')==1):?>
                                            <strong><?= __('Course Price') ?>:</strong>
                                                <?php if(empty($row->payment_required)):?>
                                                    <?=__('Free')?>
                                                <?php else: ?>
                                                    <?php echo $this->formatPrice($row->amount); ?>
                                                <?php endif; ?>

                                        <?php endif; ?>
                                    </span>

                                </div>
                                <hr class="invis clearfix">
                                <p><?php echo limitLength($row->short_description,300); ?></p>
                                <a href="<?php echo $this->url('course-details',['id'=>$row->session_id,'slug'=>safeUrl($row->session_name)]);?>" class="btn btn-default btn-sm"><?= __('Course') ?> <?=__('Details')?></a>
                            </div>
                        </div>

                    </div>



                <?php endforeach; ?>





        </div>
    </div>


    <nav class="text-center">
        <?php
        // add at the end of the file after the table

        echo $this->paginationControl(
        // the paginator object
            $this->paginator,
            // the scrolling style
            'sliding',
            // the partial to use to render the control
            array('partial/paginator.phtml', 'Application'),
            // the route to link to when a user clicks a control link
            array(
                'route' => 'courses',
            )
        );

        ?>
    </nav>




</div>
    </section>
<?php $this->headScript()->prependFile($this->basePath() . '/static/readmore/readmore.min.js')
?>
<script>
    $(function(){
        $('article.readmore').readmore({
            collapsedHeight : 70
        });
    });

</script>