   <?php  $this->headTitle('Change Your Password') ?>


            <!--container starts-->
           <div class="container"  >
           	<!--primary starts-->
            	 
          <form method="post" action="<?php echo $this->url('application/password') ?>">
              <?php echo $this->formElement($form->get('security')); ?>
  <?php echo $this->alert($this->flashMessenger()->render(),@$mode); ?>
		   <?php echo $this->alert(@$message,@$mode); ?>
<div class="form-group">
<label for="password"><?= __('new-password') ?></label>
<input class="form-control" type="password" name="password" required="required"/>

</div>

<div class="form-group">
<label for="confirm_password"><?= __('Confirm Password') ?></label>
<input class="form-control" type="password" name="confirm_password" required="required"/>

</div>


	<div class="form-footer">
								<button type="submit" class="btn btn-primary"><?= __('Submit') ?></button> 
							</div>

</form>
          
            
           </div>
           
             <!--container ends-->
         