<?php  $this->headTitle($pageTitle) ?>


<!--breadcrumb-section ends-->
<!--container starts-->
<div class="container" style="background-color: white; min-height: 400px;   padding-bottom:50px; margin-bottom: 10px;   " >
    <!--primary starts-->

    <div class="box-body">

        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                <tr>

                    <th><?= __('survey') ?></th>
                    <th><?= __('Questions') ?></th>
                    <th class="text-right1" ></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($paginator as $row): ?>
                    <tr>
                        <td><?php echo $row->name; ?></td>
                        <td><?php echo $questionTable->getTotalQuestions($row->survey_id);?></td>
                        <td >
                               <a target="_blank" href="<?php echo $this->url('survey',array('hash'=>$row->hash));?>" class="btn btn-primary " ><i class="fa fa-play"></i> <?= __('Take Survey') ?></a>
                         </td>

                    </tr>
                <?php endforeach; ?>

                </tbody>
            </table>
        </div>
        <?php
        // add at the end of the file after the table
        echo $this->paginationControl(
        // the paginator object
            $this->paginator,
            // the scrolling style
            'sliding',
            // the partial to use to render the control
            array('partial/paginator.phtml', 'Admin'),
            // the route to link to when a user clicks a control link
            array(
                'route' => 'application/default',
                'controller'=>'student',
                'action'=>'surveys'
            )
        );
        ?>
    </div>


</div>

<!--container ends-->
