   <?php  $this->headTitle($pageTitle) ?>


            <!--container starts-->
           <div class="container" style="min-height: 400px"  >
           	<!--primary starts-->
            	 
    		<?php echo $row->content?>

               <?php $shortName = $this->getSetting('general_disqus'); if(!empty($shortName)):?>
                   <script type="text/javascript">
                       /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
                       var disqus_shortname = '<?php echo trim($shortName); ?>'; // required: replace example with your forum shortname

                       /* * * DON'T EDIT BELOW THIS LINE * * */
                       (function () {
                           var s = document.createElement('script'); s.async = true;
                           s.type = 'text/javascript';
                           s.src = '//' + disqus_shortname + '.disqus.com/count.js';
                           (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
                       }());
                   </script>
               <?php endif; ?>
           </div>



           
             <!--container ends-->
         