<?php  $this->headTitle(__('Welcome')) ?>
<div class="subpage-head has-margin-bottom" style=" padding-top: 0px;">
    <div class="container">
        <h3><?= __('registration-successful') ?></h3>
    </div>
</div>

<!--breadcrumb-section ends-->
<!--container starts-->
<div class="container" style="background-color: white; min-height: 400px;   padding-bottom:50px; margin-bottom: 10px;   " >
    <!--primary starts-->

    <div class="box-body">

    <p><?= __('registration-successful-msg') ?></p>
  <p><?php echo $this->getSetting('regis_email_message'); ?></p>


    </div>


</div>

<!--container ends-->
