<?php $this->headTitle($pageTitle); ?>
<div class="container box">
    <table class="table table-stripped">
        <thead>
        <tr>
            <th><?php echo $this->getSetting('label_session_course','Session/Course')?></th>
            <th><?= __('Fee') ?></th>
        </tr>
        </thead>
        <tbody>

        <tr>
            <td><?php echo $row->session_name?></td>
            <td><?php echo $this->formatPrice($row->amount) ?></td>
        </tr>

        </tbody>

    </table>

    <div class="row">
        <div class="col-md-4 col-md-offset-6">
            <h4><?= __('select-payment-method') ?></h4>
            <form class="form" action="<?php echo $this->url('application/default',['controller'=>'payment','action'=>'method']); ?>" method="post">
            <table class="table">
                <?php $count = 0; ?>
                <?php foreach($methods as $method):?>
                <tr>
                    <td><input  <?php if($count==0):?>  checked="checked" <?php endif; ?> required="required" type="radio" name="code" value="<?php echo $method->code ?>"/> </td>
                    <td><?php echo $method->method_label ?></td>
                </tr>
                <?php $count++; ?>
                <?php endforeach; ?>
            </table>
                <button class="btn btn-primary btn-lg" type="submit"><?= __('Make Payment') ?></button>
            </form>
        </div>
    </div>
</div>