<?php $this->headTitle(__('blog').' - '.$row->title)?>
<section id="mu-page-breadcrumb" >
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="mu-page-breadcrumb-area">
                    <h2>Blog</h2>
                    <ol class="breadcrumb">
                        <li><a href="<?=$this->basePath()?>/"><?=__('Home')?></a></li>
                        <li><a href="<?=$this->url('news')?>"><?= __('Blog') ?></a></li>
                        <li class="active"><?= __('Blog Post') ?></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</section>


<section id="mu-course-content">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="mu-course-content-area">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <!-- start course content container -->
                            <div class="mu-course-container mu-blog-single">
                                <div class="row">
                                    <div class="col-md-12">
                                        <article class="mu-blog-single-item">
                                            <?php if(!empty($row->picture)):?>
                                                <figure class="mu-blog-single-img">
                                                    <a href="#"><img  src="<?php echo resizeImage($row->picture, 750, 500, $this->basePath());?>"></a>
                                                    <figcaption class="mu-blog-caption">
                                                        <h3><a href="#"><?=$row->title?></a></h3>
                                                    </figcaption>
                                                </figure>
                                            <?php endif; ?>
                                            <div class="mu-blog-meta">
                                                <a href="#"><?php echo date('d/M/Y',$row->date)?></a>
                                            </div>
                                            <div class="mu-blog-description">
                                                <p><?php echo $row->content ?></p>

                                            </div>

                                        </article>
                                        <?php $shortName = $this->getSetting('general_disqus'); if(!empty($shortName)):?>
                                            <script type="text/javascript">
                                                /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
                                                var disqus_shortname = '<?php echo trim($shortName); ?>'; // required: replace example with your forum shortname

                                                /* * * DON'T EDIT BELOW THIS LINE * * */
                                                (function () {
                                                    var s = document.createElement('script'); s.async = true;
                                                    s.type = 'text/javascript';
                                                    s.src = '//' + disqus_shortname + '.disqus.com/count.js';
                                                    (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
                                                }());
                                            </script>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                            <!-- end course content container -->
                            <!-- start blog navigation -->


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>