<?php if(isset($pageTitle))  $this->headTitle($pageTitle) ?>

<!-- Page breadcrumb -->
<section id="mu-page-breadcrumb">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="mu-page-breadcrumb-area">
                    <h2><?=$pageTitle?></h2>
                    <ol class="breadcrumb">
                        <li><a href="<?=$this->basePath()?>/"><?=__('Home')?></a></li>
                        <li class="active"><?=$pageTitle?></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Start gallery  -->
<section id="mu-gallery">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="mu-gallery-area">
                    <!-- start title -->
                    <div >
                        <p> <?php echo $content; ?>
                        </p>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>
<!-- End gallery  -->

