<?php $this->layout('layout/adminlogin'); ?>
<section class="login_content" >
    <?php




    $form->prepare();
    //$form->setAttribute('action', $this->basepath().'/users/login/process');
    $form->setAttribute('action', $this->url('admin/change-password').'?token='.$token);
    $form->setAttribute('method', 'post');
    $form->setAttribute('id', 'loginform');
    $form->setAttribute('class', 'form-horizontal');

    $form->get('password')->setAttribute('class','form-control');
    $form->get('password')->setAttribute('placeholder','New Password');

    $form->get('confirm_password')->setAttribute('class','form-control');
    $form->get('confirm_password')->setAttribute('placeholder','Confirm Password');


    //$form->get('submit')->setAttribute('class','btn btn-danger');

    echo $this->form()->openTag($form);
    ?>
        <?php echo $this->formElement($form->get('security')); ?>
        <h1>  <?php if(isset($message)): ?>
                <?php echo $message; ?>
            <?php else: ?>
                Change Your Password
            <?php endif; ?></h1>
        <div>
            <?php
            echo $this->formElement($form->get('password'));
            echo $this->formElementErrors($form->get('password'));
            ?>
        </div>

        <div>
            <?php
            echo $this->formElement($form->get('confirm_password'));
            echo $this->formElementErrors($form->get('confirm_password'));
            ?>
        </div>

        <div>

            <button class="btn w-md btn-bordered btn-primary waves-effect waves-light" type="submit">Change Password</button>

            <a class="reset_pass" href="<?php echo $this->url('admin/signin');?>">Login</a>
        </div>

        <div class="clearfix"></div>

        <div class="separator">



            <div>
                <img style="max-width: 100%" src="<?php echo $this->basePath() ?>/img/logo-black.png" alt=""/>

            </div>
        </div>
    </form>
</section>