<?php if($this->getSetting('banner_status')==1): ?>
<meta name="google-play-app" content="app-id=<?=$this->getSetting('banner_android_id')?>">
<meta name="apple-itunes-app" content="app-id=<?=$this->getSetting('banner_ios_id')?>">
<link href="<?php echo $this->basePath(); ?>/static/jasny-smartbanner/jquery.smartbanner.css" rel="stylesheet" type="text/css" />
<script src="<?php echo $this->basePath(); ?>/static/jasny-smartbanner/jquery.smartbanner.js"></script>
<script type="text/javascript">
    jQuery(function(){
        jQuery.smartbanner({
            title: '<?=$this->getSetting('banner_app_name')?>', // What the title of the app should be in the banner (defaults to <title>)
            author: 'Intermatics', // What the author of the app should be in the banner (defaults to <meta name="author"> or hostname)
            price: 'FREE', // Price of the app
            icon: '<?=$this->getSetting('banner_icon_url')?>', // The URL of the icon (defaults to <link>)
            button: 'VIEW' // Text on the install button
        });

    });

</script>

<?php endif; ?>