<?php
$form->prepare();
$form->setAttribute('action', $this->url('admin/default',array('controller'=>'smsgateway','action'=>'customize','id'=>$id)));
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');

echo $this->form()->openTag($form);
?>
    <div class="row">
        <div >
            <div class="box">

                <div class="box-body">

                    <?php foreach($options as $row):?>

                        <div class="form-group">
                            <div class="col-sm-2">
                                <?php     echo $this->formLabel($form->get($row->key));   ?>
                            </div>
                            <div class="col-sm-10">
                                <?php if($row->type == 'radio'):?>
                                    <?php  echo $this->formRadio($form->get($row->key));    ?>
                                <?php else:?>
                                    <?php  echo $this->formElement($form->get($row->key));    ?>
                                <?php endif; ?>
                            </div>
                        </div>

                    <?php endforeach; ?>





                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div >
            <button class="btn btn-primary" type="submit"><?=__('save-changes')?></button>
        </div><!--end .col-lg-12 -->
    </div>

<?php echo $this->form()->closeTag($form);  ?>