<div class="box">

<div class="box-body">


<form method="post" action="<?php echo $this->url('admin/default',array('controller'=>'account','action'=>'email')) ?>">

<div class="form-group">
<label for="email"><?= __('new-email') ?></label>
<input class="form-control" type="text" name="email" required="required"/>

</div>
	<div class="form-footer">
								<button type="submit" class="btn btn-primary"><?= __('submit') ?></button> 
							</div>

</form>


</div>

</div>


