<div class="box">

<div class="box-body">


<form method="post" action="<?php echo $this->url('admin/default',array('controller'=>'account','action'=>'password')) ?>">

<div class="form-group">
<label for="password"><?= __('password') ?></label>
<input class="form-control" type="password" name="password" required="required"/>

</div>

<div class="form-group">
<label for="confirm_password"><?= __('confirm-password') ?></label>
<input class="form-control" type="password" name="confirm_password" required="required"/>

</div>


	<div class="form-footer">
								<button type="submit" class="btn btn-primary"><?= __('submit') ?></button> 
							</div>

</form>


</div>

</div>


