<div class="row">
			<div >
				<div class="box">
					 
					<div class="box-body">
						               <?php  
$form->prepare();
$form->setAttribute('action', $this->url('admin/default',array('controller'=>'setting','action'=>$action,'id'=>$id)));
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');  
$form->setAttribute('class', 'form-horizontal');     

echo $this->form()->openTag($form);   
?> 
                          
                                                
                                  
							 
									<div class="form-group"> 
											<?php     echo $this->formLabel($form->get('name'));
   
?>
										 <?php     echo $this->formElement($form->get('name'));
   
?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('name'));?></p>
									 
									</div>
								 
                                
                                




                        <div class="form-group">
                            <?php     echo $this->formLabel($form->get('type'));

                            ?>
                            <?php     echo $this->formElement($form->get('type'));

                            ?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('type'));?></p>

                        </div>


                        <div class="form-group options">
                            <?php     echo $this->formLabel($form->get('options'));

                            ?>
                            <?php     echo $this->formElement($form->get('options'));

                            ?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('options'));?></p>

                        </div>




                        <div class="form-group">
                            <?php     echo $this->formLabel($form->get('required'));

                            ?>
                            <?php     echo $this->formElement($form->get('required'));

                            ?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('required'));?></p>

                        </div>




                        <div class="form-group hint">
                            <?php     echo $this->formLabel($form->get('placeholder'));

                            ?>
                            <?php     echo $this->formElement($form->get('placeholder'));

                            ?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('placeholder'));?></p>

                        </div>


                        <div class="form-group">
                            <?php     echo $this->formLabel($form->get('sort_order'));

                            ?>
                            <?php     echo $this->formElement($form->get('sort_order'));

                            ?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('sort_order'));?></p>

                        </div>

                        <div class="form-group">
                            <?php     echo $this->formLabel($form->get('status'));

                            ?>
                            <?php     echo $this->formElement($form->get('status'));

                            ?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('status'));?></p>

                        </div>





                        <div class="form-footer">
								<button type="submit" class="btn btn-primary"><?=__('save-changes')?></button>
							</div>
						<?php echo $this->form()->closeTag($form);  ?>
					</div>
				</div><!--end .box -->
			</div><!--end .col-lg-12 -->
		</div>

<script>
    $('select[name=type]').change(function(){
        showOptions();
    });

    function showOptions(){
        if($('select[name=type]').val()=='select' || $('select[name=type]').val()=='radio' ){
            $('.options').show();
        }
        else{
            $('.options').hide();
        }

    }

    showOptions();
</script>

<script>
    $('select[name=type]').change(function(){
        showHint();
    });

    function showHint(){
        if($('select[name=type]').val()=='text' || $('select[name=type]').val()=='textarea' ){
            $('.hint').show();
        }
        else{
            $('.hint').hide();
        }

    }

    showHint();
</script>