<?php  $this->headTitle($pageTitle) ?>
<div class="row">

    <div class="col-md-9">

        <?php foreach($paginator as $row): ?>

        <div class="panel panel-default paper-shadow" data-z="0.5">
            <div class="panel-body">

                <div class="media media-clearfix-xs">
                    <div class="media-left text-center">
                        <div class="cover width-150 width-100pc-xs overlay cover-image-full hover margin-v-0-10">
                            <span class="img icon-block height-130 bg-default"></span>
                            <span class="overlay overlay-full padding-none icon-block bg-default">
                        <span class="v-center">


                            <?php if(!empty($row->picture)): ?>

                                            <a href="<?php echo $this->url('course-details',['id'=>$row->session_id,'slug'=>safeUrl($row->session_name)]);?>" class="thumbnail" style="border: none; margin-bottom: 0px">
                                                <img src="<?php echo resizeImage($row->picture,150,130,$this->basePath()); ?>" >
                                            </a>
                             <?php else: ?>
                                <i class="fa fa-book"></i>
                            <?php endif; ?>
                        </span>
                    </span>
                            <a href="<?php echo $this->url('course-details',['id'=>$row->session_id,'slug'=>safeUrl($row->session_name)]);?>" class="overlay overlay-full overlay-hover overlay-bg-white">
                       
                            </a>
                        </div>
                    </div>
                    <div class="media-body">
                        <h4 class="text-headline margin-v-5-0"><a href="<?php echo $this->url('course-details',['id'=>$row->session_id,'slug'=>safeUrl($row->session_name)]);?>"><?php echo $row->session_name ?></a></h4>

                        <p><?php echo limitLength($row->short_description,300); ?></p>
                        <p>
                            <?php if($this->getSetting('general_show_fee')==1):?>
                                <strong>
                                    <?php if(empty($row->payment_required)):?>
                                        <?= __('free') ?>
                                    <?php else: ?>
                                        <?php echo $this->formatPrice($row->amount); ?>
                                    <?php endif; ?>
                                </strong>
                            <?php endif; ?>
                        </p>

                        <?php $session = \Application\Entity\Session::find($row->session_id); ?>
                        <hr class="margin-v-8" />

                        <div class="row">
                            <?php foreach($session->sessionInstructors as $instructor):?>
                            <div class="col-md-4">
                                <div class="media v-middle">
                                    <div class="media-left">
                                        <img src="<?=profilePictureUrl($instructor->account->picture,$this->basePath())?>" alt="People" class="img-circle width-40"/>
                                    </div>
                                    <div class="media-body">
                                        <h4><a href="#"  data-toggle="modal" data-target="#instructorModal<?=$instructor->session_instructor_id?>"><?=$instructor->account->first_name?> <?=$instructor->account->last_name?></a><br/></h4>
                                        <?= __('instructor') ?>
                                    </div>
                                </div>
                            </div>





                            <?php endforeach; ?>

                        </div>
                        <a href="<?php echo $this->url('course-details',['id'=>$row->session_id,'slug'=>safeUrl($row->session_name)]);?>" class="btn btn-primary pull-right"><i class="fa fa-info-circle"></i> <?= __('details') ?></a>



                    </div>
                </div>

            </div>
        </div>

        <?php foreach($session->sessionInstructors as $instructor):?>

            <div class="modal fade" id="instructorModal<?=$instructor->session_instructor_id?>" tabindex="-1" role="dialog" aria-labelledby="instructorModal<?=$instructor->session_instructor_id?>Label">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="instructorModal<?=$instructor->session_instructor_id?>Label"><?=$instructor->account->first_name?> <?=$instructor->account->last_name?></h4>
                        </div>
                        <div class="modal-body">
                            <div class="media v-middle">
                                <div class="media-left">
                                    <img src="<?=profilePictureUrl($instructor->account->picture,$this->basePath())?>" alt="People" class="img-circle width-200"/>
                                </div>
                                <div class="media-body">
                                    <?=$instructor->account->account_description?>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary" data-dismiss="modal"><?= __('close') ?></button>
                        </div>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>


        <?php endforeach; ?>


        <?php
        // add at the end of the file after the table

        echo $this->paginationControl(
        // the paginator object
            $this->paginator,
            // the scrolling style
            'sliding',
            // the partial to use to render the control
            array('partial/paginator.phtml', 'Application'),
            // the route to link to when a user clicks a control link
            array(
                'route' => 'courses',
            )
        );

        ?>

        <br/>
        <br/>


    </div>
    <div class="col-md-3">

        <div class="panel panel-default" data-toggle="panel-collapse" data-open="true">
            <div class="panel-heading panel-collapse-trigger">
                <h4 class="panel-title"><?= __('category') ?></h4>
            </div>
            <div class="panel-body list-group">
                <ul class="list-group">
                    <li class="list-group-item">
                        <a class="list-group-link" href="<?php echo $this->url('courses') ?>"><?= __('all-courses') ?></a>
                    </li>

                    <?php foreach($categories as $category):?>
                    <li class="list-group-item">
                        <a class="list-group-link" href="<?php echo $this->url('courses') ?>?group=<?php echo $category->session_category_id ?>"><?php echo $category->category_name; ?></a>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>

        <div class="panel panel-default" data-toggle="panel-collapse" data-open="false">
            <div class="panel-heading panel-collapse-trigger">
                <h4 class="panel-title"><?= __('Filter') ?></h4>
            </div>
            <div class="panel-body">
                <form id="filterform" class="form" role="form"  method="get" action="<?php echo $this->url('courses'); ?>">
                <div class="form-group input-group margin-none">
                    <div class="row margin-none">
                        <input type="hidden" name="group" value="<?php echo $group ?>"/>

                        <div class="form-group">
                            <label  for="filter"><?= __('search') ?></label>
                            <?php echo $this->formElement($text) ?>
                        </div>
                        <div  class="form-group">
                            <label  for="group"><?= __('sort') ?></label>
                            <?php echo $this->formElement($sortSelect) ?>
                        </div>

                        <div style="padding-top: 35px">
                            <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> <?= __('filter') ?></button>
                            <button type="button" onclick="$('#filterform input, #filterform select').val(''); $('#filterform').submit();" class="btn btn-inverse"><?= __('clear') ?></button>

                        </div>

                    </div>

                </div>
                </form>
            </div>
        </div>


    </div>

</div>