<?php  $this->headTitle($pageTitle) ?>
<div id="content">
    <div class="container">
        <div  class="row col-md-4 col-md-offset-4 " id="comment-form-wrapper">
            <?php if($display):?>
                <div class="comment_form_holder ">

                    <?php if(isset($message)): ?>

                        <?php echo $message; ?>
                    <?php else: ?>
                        <h2 class="text-light" style="text-align:center">    Reset Your Password </h2>
                        <div style="text-align:center">Enter your new password</div>
                    <?php endif; ?>

                    <br/>

                    <?php




                    $form->prepare();
                    //$form->setAttribute('action', $this->basepath().'/users/login/process');
                    $form->setAttribute('action', $this->url('application/change-password').'?token='.$token);
                    $form->setAttribute('method', 'post');
                    $form->setAttribute('id', 'loginform');

                    $form->get('password')->setAttribute('class','form-control');
                    $form->get('password')->setAttribute('placeholder','New Password');

                    $form->get('confirm_password')->setAttribute('class','form-control');
                    $form->get('confirm_password')->setAttribute('placeholder','Confirm Password');


                    //$form->get('submit')->setAttribute('class','btn btn-danger'); 

                    echo $this->form()->openTag($form);
                    ?>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-lock"></i></span>

                            <?php
                            echo $this->formElement($form->get('password'));
                            echo $this->formElementErrors($form->get('password'));
                            ?>
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-lock"></i></span>

                            <?php
                            echo $this->formElement($form->get('confirm_password'));
                            echo $this->formElementErrors($form->get('confirm_password'));
                            ?>
                        </div>
                    </div>





                    <div class="row">
                        <div class="col-xs-6 text-left">

                        </div>
                        <div class="col-xs-6 text-right">
                            <button class="btn btn-primary" type="submit"><i class="fa fa-key"></i> Submit</button>
                        </div>
                    </div>
                    <?php echo $this->form()->closeTag() ?>

                </div>
            <?php else:?>
                <h2>Invalid URL</h2>
            <?php endif;?>
        </div>
        <!--end .box-body -->

    </div>
</div>