<!DOCTYPE html>
<html <?=langMeta()?>>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- App favicon -->
    <?php $icon = $this->getSetting('image_icon'); if(!empty($icon)):?>
    <link rel="shortcut icon" href="<?php echo $this->basePath(); ?>/<?php echo $this->getSetting('image_icon'); ?>">
    <?php endif; ?><!-- App title -->
    <title>Password Reset</title>

    <!-- App css -->
    <link href="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/css/core.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/css/components.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/css/icons.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/css/pages.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/css/menu.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/css/responsive.css" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/js/modernizr.min.js"></script>


</head>


<body class="bg-transparent">

<!-- HOME -->
<section>
    <div class="container-alt">
        <div class="row">
            <div class="col-sm-12">

                <div class="wrapper-page" style="margin: 3% auto;">
                    <div style="text-align: center; padding-bottom: 0px">
                        <?php $logo = $this->getSetting('image_logo'); if(!empty($logo)):?>
                            <a    href="<?php echo $this->url('home');?>"><img style="max-height: 90px"   src="<?php echo $this->basePath(); ?>/<?php echo $this->getSetting('image_logo'); ?>"></a>
                        <?php else:  ?>
                            <a   href="<?php echo $this->url('home');?>"> <h2><?php echo $this->getSetting('general_site_name'); ?></h2></a>
                        <?php endif; ?>
                    </div>
                    <?php echo $this->alert(html_entity_decode($this->flashMessenger()->render())); ?>
                    <div class="m-t-10 account-pages">

                        <div class="text-center account-logo-box">
                            <h2 class="text-uppercase_">
                                <a href="#" class="text-success">
                                    <span style="color: white">Password Reset</span>

                                </a>

                            </h2>
                            <h4   style="color: white" class="text-uppercase_ font-bold m-b-0"><?php if(isset($message)): ?>
                                    <?php echo $message; ?>
                                <?php endif; ?></h4>
                        </div>
                        <div class="account-content">

                            <form class="form-horizontal" action="<?php echo $this->url('application/reset') ?>" method="post">
                                <?php echo $this->formElement($form->get('security')); ?>



                                <div class="form-group ">
                                    <div class="col-xs-12">
                                        <input placeholder="Your email address" type="text" class="form-control" name="email"/>

                                    </div>
                                </div>



                                <div class="form-group account-btn text-center m-t-10">
                                    <div class="col-xs-12">
                                        <button class="btn w-md btn-bordered btn-danger waves-effect waves-light" type="submit">Reset</button>
                                    </div>
                                </div>

                            </form>

                            <div class="clearfix"></div>

                        </div>
                    </div>
                    <!-- end card-box-->


                    <div class="row m-t-50">
                        <div class="col-sm-12 text-center">
                            <p class="text-muted">Don't have an account? <a href="<?php echo $this->url('application/register')?>" class="text-primary m-l-5"><b>Sign Up</b></a></p>
                        </div>
                    </div>

                </div>
                <!-- end wrapper -->

            </div>
        </div>
    </div>
</section>
<!-- END HOME -->

<script>
    var resizefunc = [];
</script>

<!-- jQuery  -->
<script src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/js/jquery.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/js/bootstrap.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/js/detect.js"></script>
<script src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/js/fastclick.js"></script>
<script src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/js/jquery.blockUI.js"></script>
<script src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/js/waves.js"></script>
<script src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/js/jquery.slimscroll.js"></script>
<script src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/js/jquery.scrollTo.min.js"></script>

<!-- App js -->
<script src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/js/jquery.core.js"></script>
<script src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/js/jquery.app.js"></script>

</body>
</html>