<!DOCTYPE html>
<html <?=langMeta()?>>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>TrainEasy <?= __('login') ?></title>

    <!-- Bootstrap -->
    <link href="<?php echo $this->basePath(); ?>/themes/cpanel/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="<?php echo $this->basePath(); ?>/themes/cpanel/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="<?php echo $this->basePath(); ?>/themes/cpanel/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- Animate.css -->
    <link href="<?php echo $this->basePath(); ?>/themes/cpanel/vendors/animate.css/animate.min.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="<?php echo $this->basePath(); ?>/themes/cpanel/build/css/custom.min.css" rel="stylesheet">
    <?php if(defined('USER_ID')):?>
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-98793156-2', 'auto');
            ga('send', 'pageview');

        </script>
    <?php endif; ?>
    <?php echo $this->getSetting('general_header_scripts');?>
</head>

<body class="login">
<div>
    <a class="hiddenanchor" id="signup"></a>
    <a class="hiddenanchor" id="signin"></a>

    <div class="login_wrapper">
        <div class="animate form login_form">
            <?php echo $content ?>
        </div>


    </div>
</div>
<script src="<?php echo $this->basePath(); ?>/themes/cpanel/vendors/jquery/dist/jquery.min.js"></script>
<?php echo $this->getSetting('general_foot_scripts');?>
</body>
</html>
