<!DOCTYPE html>
<html <?=langMeta()?>>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?php echo $this->headTitle('Payment - '.$this->getSetting('general_site_name')) ?>

    <!-- Bootstrap -->
    <link href="<?php echo $this->basePath(); ?>/themes/cpanel/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="<?php echo $this->basePath(); ?>/themes/cpanel/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <!-- Animate.css -->

    <!-- Custom Theme Style -->
    <link href="<?php echo $this->basePath(); ?>/themes/cpanel/build/css/custom.min.css" rel="stylesheet">
<style>
    div.box {

        height: auto;
        padding: 10px;
        padding-right: 10px;
        padding-left: 10px;
        overflow: auto;
        border: none;
        background-color: #ffffff;

    }
</style>
</head>

<body class="login">
<div>
    <a class="hiddenanchor" id="signup"></a>
    <a class="hiddenanchor" id="signin"></a>

    <div class="login_wrapper">
        <div class="animate form login_form">
            <?php echo $content ?>
        </div>


    </div>
</div>
</body>
</html>
