<?php
$children = $this->viewModel()->getCurrent()->getChildren();
foreach($children as $action) {
    if ($action->captureTo() == 'content') {
        break;
    }


}
$this->headTitle()->setSeparator(' - ')->setAutoEscape(false);

$basePath = $this->basePath();
$this->headLink()
;


echo $this->doctype();
?>
<html<?=langMeta()?>>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Student Portal">
    <meta name="author" content="Intermatics">

    <link rel="shortcut icon" href="<?php echo $this->basePath(); ?>/<?php echo $this->getSetting('image_logo'); ?>">

    <?php echo $this->headTitle('Student Portal - '.$this->getSetting('general_site_name')) ?>

    <!-- App css -->
    <link href="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/css/core.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/css/components.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/css/icons.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/css/pages.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/css/menu.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/css/responsive.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/themes/ucpanel/plugins/switchery/switchery.min.css">
    <link href="<?php echo $this->basePath(); ?>/static/fontawesome5/web-fonts-with-css/css/fontawesome-all.min.css" rel="stylesheet">



    <link type="text/css" rel="stylesheet" href="<?php echo $this->basePath(); ?>/jquery-ui/css/ui-lightness/jquery-ui-1.10.4.css" />
    <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/admin.css">


    <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/js/modernizr.min.js"></script>

    <!-- jQuery  -->
    <script src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/js/jquery.min.js"></script>

    <script src="<?php echo $this->basePath(); ?>/jquery-ui-1.11.4/jquery-ui.min.js"></script>

    <link href="<?php echo $this->basePath(); ?>/static/select2/css/select2.min.css" rel="stylesheet" />
    <script src="<?php echo $this->basePath(); ?>/static/select2/js/select2.min.js"></script>

    <script src="<?php echo $this->basePath(); ?>/app/lib.js"></script>

    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    <!-- Scripts -->
    <?php echo $this->headScript(); ?>

    <?php echo $this->headStyle(); ?>

    <?php if(defined('USER_ID')):?>
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-98793156-2', 'auto');
            ga('send', 'pageview');

        </script>
    <?php endif; ?>

    <?php if(defined('ENABLE_CHAT')):?>
        <?php echo $this->getSetting('general_chat_code'); ?>
    <?php endif; ?>

    <?php echo $this->getSetting('general_header_scripts');?>
    <style>
        #topnav {
            position: static;
        }
        .wrapper {
            padding-top: 0px;
        }
        #topnav .topbar-main {
            background-color: #f3f3f3;
        }
        #topnav .topbar-main .nav > li > a {
            border: 2px solid rgba(149, 145, 145, 0.7) !important;
            color: rgba(90, 87, 87, 0.7);
        }
        #topnav .topbar-main .nav > li > a:focus, #topnav .topbar-main .nav > li > a:hover {

            color: #5c5252;
        }
        #topnav .navbar-toggle span {

            background-color: rgba(20, 17, 17, 0.8);
        }
        #topnav .navbar-toggle:hover span{
            background-color:#ccc
        }
    </style>
</head>


<body>


<!-- Navigation Bar-->
<header id="topnav">
    <div class="topbar-main">
        <div class="container">

            <!-- Logo container-->
            <div class="logo">
                <!-- Text Logo -->
                <!--<a href="index.html" class="logo">-->
                <!--Zircos-->
                <!--</a>-->
                <!-- Image Logo -->
                <a href="<?php echo $this->url('home'); ?>" class="logo">
                    <img src="<?php echo $this->basePath(); ?>/<?php echo $this->getSetting('image_logo'); ?>" alt="" height="30">
                </a>

            </div>
            <!-- End Logo container-->


            <div class="menu-extras">

                <ul class="nav navbar-nav navbar-right pull-right">

                    <?php if(false): ?>
                    <li class="navbar-c-items">
                        <form role="search" class="navbar-left app-search pull-left hidden-xs">
                            <input type="text" placeholder="Search..." class="form-control">
                            <a href=""><i class="fa fa-search"></i></a>
                        </form>
                    </li>

                    <li class="dropdown navbar-c-items">
                        <a href="#" class="right-menu-item dropdown-toggle" data-toggle="dropdown">
                            <i class="mdi mdi-email"></i>
                            <span class="badge up bg-danger">8</span>
                        </a>

                        <ul class="dropdown-menu dropdown-menu-right arrow-dropdown-menu arrow-menu-right dropdown-lg user-list notify-list">
                            <li class="text-center">
                                <h5>Messages</h5>
                            </li>
                            <li>
                                <a href="#" class="user-list-item">
                                    <div class="avatar">
                                        <img src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/images/users/avatar-2.jpg" alt="">
                                    </div>
                                    <div class="user-desc">
                                        <span class="name">Patricia Beach</span>
                                        <span class="desc">There are new settings available</span>
                                        <span class="time">2 hours ago</span>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="user-list-item">
                                    <div class="avatar">
                                        <img src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/images/users/avatar-3.jpg" alt="">
                                    </div>
                                    <div class="user-desc">
                                        <span class="name">Connie Lucas</span>
                                        <span class="desc">There are new settings available</span>
                                        <span class="time">2 hours ago</span>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="user-list-item">
                                    <div class="avatar">
                                        <img src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/images/users/avatar-4.jpg" alt="">
                                    </div>
                                    <div class="user-desc">
                                        <span class="name">Margaret Becker</span>
                                        <span class="desc">There are new settings available</span>
                                        <span class="time">2 hours ago</span>
                                    </div>
                                </a>
                            </li>
                            <li class="all-msgs text-center">
                                <p class="m-0"><a href="#">See all Messages</a></p>
                            </li>
                        </ul>
                    </li>

                    <li class="dropdown navbar-c-items">
                        <a href="#" class="right-menu-item dropdown-toggle" data-toggle="dropdown">
                            <i class="mdi mdi-bell"></i>
                            <span class="badge up bg-success">4</span>
                        </a>

                        <ul class="dropdown-menu dropdown-menu-right arrow-dropdown-menu arrow-menu-right dropdown-lg user-list notify-list">
                            <li class="text-center">
                                <h5>Notifications</h5>
                            </li>
                            <li>
                                <a href="#" class="user-list-item">
                                    <div class="icon bg-info">
                                        <i class="mdi mdi-account"></i>
                                    </div>
                                    <div class="user-desc">
                                        <span class="name">New Signup</span>
                                        <span class="time">5 hours ago</span>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="user-list-item">
                                    <div class="icon bg-danger">
                                        <i class="mdi mdi-comment"></i>
                                    </div>
                                    <div class="user-desc">
                                        <span class="name">New Message received</span>
                                        <span class="time">1 day ago</span>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="user-list-item">
                                    <div class="icon bg-warning">
                                        <i class="mdi mdi-settings"></i>
                                    </div>
                                    <div class="user-desc">
                                        <span class="name">Settings</span>
                                        <span class="time">1 day ago</span>
                                    </div>
                                </a>
                            </li>
                            <li class="all-msgs text-center">
                                <p class="m-0"><a href="#">See all Notification</a></p>
                            </li>
                        </ul>
                    </li>
                    <?php endif; ?>


                    <li class="dropdown navbar-c-items">
                        <a href="" class="dropdown-toggle waves-effect waves-light profile" data-toggle="dropdown" aria-expanded="true">
                            <?php if(empty($this->getStudent()->picture)):?>
                            <i class="fa fa-user"></i>
                            <?php elseif(isUrl($this->getStudent()->picture)):?>
                                <img src="<?=$this->getStudent()->picture?>" alt=""/>
                            <?php else: ?>
                                <img src="<?php echo resizeImage($this->getStudent()->picture,128,128,$this->basePath()); ?>" alt=""/>

                            <?php endif; ?>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right arrow-dropdown-menu arrow-menu-right user-list notify-list">
                            <li class="text-center">
                                <h5>Hi, <?php echo $this->getStudent()->first_name?></h5>
                            </li>
                            <li><a href="<?php echo $this->url('application/profile')?>"><i class="ti-user m-r-5"></i> Profile</a></li>
                            <li><a href="<?php echo $this->url('application/password')?>"><i class="ti-lock m-r-5"></i> Change Password</a></li>

                            <li><a href="<?php echo $this->url('application/logout')?>"><i class="ti-power-off m-r-5"></i> Logout</a></li>

                        </ul>

                    </li>
                </ul>
                <div class="menu-item">
                    <!-- Mobile menu toggle-->
                    <a class="navbar-toggle">
                        <div class="lines">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </a>
                    <!-- End mobile menu toggle-->
                </div>
            </div>
            <!-- end menu-extras -->

        </div> <!-- end container -->
    </div>
    <!-- end topbar-main -->

    <div class="navbar-custom">
        <div class="container">
            <div id="navigation">
                <!-- Navigation Menu-->
                <ul class="navigation-menu">

                    <li>
                        <a  href="<?php echo $this->url('application/dashboard'); ?>"><i class="mdi mdi-view-dashboard"></i> Dashboard</a>
                    </li>




                    <li class="has-submenu">
                        <a href="#" ><i class="fa fa-chalkboard-teacher fa-fw"></i> <span> <?php echo $this->getSetting('label_my_sessions','My Sessions &amp; Courses')?> </span> <span class="fa fa-chevron-down"></span></a>
                        <ul class="submenu megamenu">
                            <li>
                                <ul>
                                    <li><a href="<?php echo $this->url('application/mysessions');?>">View All</a></li>

                                    <?php if($this->getSetting('menu_show_attended')==1):?>
                                        <li> <a href="<?php echo $this->url('application/classes')?>"> <?php echo $this->getSetting('label_classes_attended','Classes Attended')?>  </a>  </li>
                                    <?php endif;?>
                                    <li><a href="<?php echo $this->url('application/default',['controller'=>'course','action'=>'bookmarks']) ?>">Bookmarks</a></li>

                                </ul>
                            </li>
                            <li>
                                <ul>
                                    <li>
                                        <span>Tests</span>
                                    </li>
                                    <?php if($this->getSetting('menu_show_tests')==1):?>
                                        <li> <a href="<?php echo $this->url('application/test')?>"><i class="fa fa-check-circle fa-fw"></i> <?php echo $this->getSetting('label_take_test','Browse Tests')?>  </a>  </li>
                                        <li> <a href="<?php echo $this->url('application/default',['controller'=>'test','action'=>'statement'])?>"><i class="fa fa-file-alt  fa-fw"></i> Statement of Result</a>  </li>
                                    <?php endif;?>

                                    <li>
                                        <span>Resources</span>
                                    </li>
                                    <?php if($this->getSetting('menu_show_certificates')==1):?>
                                        <li> <a href="<?php echo $this->url('application/certificates')?>"><i class="fa fa-file-pdf-o fa-fw"></i> <?php echo $this->getSetting('label_certificates','Certificates')?>  </a>  </li>
                                    <?php endif;?>
                                    <?php if($this->getSetting('menu_show_downloads')==1):?>
                                        <li> <a href="<?php echo $this->url('application/downloads')?>"><i class="fa fa-download fa-fw"></i> <?php echo $this->getSetting('label_downloads','Downloads')?>  </a>  </li>
                                    <?php endif;?>
                                </ul>
                            </li>

                        </ul>
                    </li>


                    <li  class="has-submenu" >
                        <a href="#" ><i class="fa fa-user-plus fa-fw"></i> <span> Enroll </span> <span class="fa fa-chevron-down"></span></a>
                        <ul class="submenu">
                            <?php if($this->getSetting('menu_show_sessions')==1):?>
                                <li><a href="<?php echo $this->url('courses')?>"><?php echo $this->getSetting('label_courses','Online Courses')?></a></li>
                            <?php endif; ?>
                            <?php if($this->getSetting('menu_show_courses')==1):?>
                                <li> <a href="<?php echo $this->url('sessions')?>"><?php echo $this->getSetting('label_sessions','Upcoming Sessions')?> </a>  </li>
                            <?php endif; ?>
                        </ul>
                    </li>

                    <li  class="has-submenu" >
                        <a href="#" ><i class="fa fa-edit fa-fw"></i> <span> <?php echo $this->getSetting('label_homework','Homework')?> </span> <span class="fa fa-chevron-down"></span></a>
                        <ul class="submenu">
                            <li><a href="<?php echo $this->url('application/assignments');?>">View All</a></li>

                            <li> <a href="<?php echo $this->url('application/assignment-submissions')?>">My Submissions </a>  </li>


                        </ul>
                    </li>

                    <?php if($this->getSetting('menu_show_notes')==1):?>
                        <li> <a href="<?php echo $this->url('application/notes')?>"><i class="fa  fa-book fa-fw"></i> <?php echo $this->getSetting('label_revision_notes','Revision Notes')?>  </a>  </li>
                    <?php endif;?>


                    <?php if($this->getSetting('menu_show_discussions')==1):?>

                        <li  class="has-submenu" >
                            <a href="#" ><i class="fa  fa-comments fa-fw"></i> <span> <?php echo $this->getSetting('label_discussion','Discuss')?>  </span> <span class="fa fa-chevron-down"></span></a>
                            <ul class="submenu">
                                <li><a href="<?php echo $this->url('application/discussions')?>">Instructor Chat</a></li>

                                <li> <a href="<?php echo $this->url('application/default',['controller'=>'forum','action'=>'index'])?>">Student Forum </a>  </li>


                            </ul>
                        </li>


                    <?php endif;?>




















                </ul>
                <!-- End navigation menu -->
            </div> <!-- end #navigation -->
        </div> <!-- end container -->
    </div> <!-- end navbar-custom -->
</header>
<!-- End Navigation Bar-->


<div class="wrapper">
    <div class="container">

        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">


                    <div class="btn-group pull-right">


                        <?php if(!isset($action->hideCrumbs)):?>
                        <?php if(isset($action->customCrumbs)): ?>
                        <ol class="breadcrumb hide-phone p-0 m-0">
                            <?php $count=0;?>
                            <?php  foreach($action->customCrumbs as $key=>$value):?>



                                <li>
                                    <?php
                                    // if this isn't the last page, add a link and the separator
                                    if ($count < count($action->customCrumbs) - 1):
                                        ?>
                                        <a href="<?php echo $key ?>"><?php echo $value; ?></a>

                                    <?php // otherwise, just output the name
                                    else:
                                        ?>
                                        <?php echo  $value ?>
                                    <?php endif; ?>
                                </li>
                                <?php $count++;?>


                            <?php endforeach; ?>
                        </ol>
                            <?php else: ?>
                                <?php
                                echo $this->navigation('navigation') // <-- Update this!!
                                ->breadcrumbs()
                                    ->setMinDepth(0)
                                    ->setPartial(array('partial/breadcrumb.phtml', 'Album'));
                                ?>
                            <?php endif; ?>
                        <?php endif; ?>

                    </div>


                    <h4 class="page-title"><?php echo strip_tags($action->pageTitle) ?> </h4>
                </div>
            </div>
        </div>
        <!-- end page title end breadcrumb -->


        <div class="row">
            <div class="col-sm-12">
                <div class="card-box">
                    <?php echo $this->alert(html_entity_decode($this->flashMessenger()->render()),@$action->mode); ?>

                    <?php echo $this->alert(@$action->message,@$action->mode); ?>


                    <?php  echo $this->content; ?>


                    <!-- START SIMPLE MODAL MARKUP -->
                    <div class="modal fade" id="generalModal" tabindex="-1" role="dialog" aria-labelledby="generalModalLabel" aria-hidden="true">
                        <div class="modal-dialog  modal-lg">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    <h4 class="modal-title" id="generalModalLabel"></h4>
                                </div>
                                <div class="modal-body" id="genmodalinfo">

                                </div>
                                <div class="modal-footer">

                                </div>
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->
                    <!-- END SIMPLE MODAL MARKUP -->
                    <script>
                        function openModal(title,url){
                            $('#genmodalinfo').html(' <img  src="<?php echo $this->basePath() ?>/img/ajax-loader.gif">');
                            $('#generalModalLabel').text(title);
                            $('#genmodalinfo').load(url);
                            $('#generalModal').modal();
                        }
                        function openPopup(url){
                            window.open(url, "_blank", "toolbar=no,scrollbars=yes,resizable=yes,top=500,left=500,width=400,height=400");
                            return false;
                        }
                    </script>

                </div>
            </div>
        </div>
        <!-- end row -->


        <!-- Footer -->
        <footer class="footer text-right">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <?php echo $this->getSetting('footer_credits'); ?><?php $status=getenv('hidecopy'); if(empty($status)):?>
                            . Powered by <a href="https://traineasy.net">TrainEasy</a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </footer>
        <!-- End Footer -->

    </div> <!-- end container -->
</div>
<!-- end wrapper -->



<script src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/js/bootstrap.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/js/detect.js"></script>
<script src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/js/fastclick.js"></script>
<script src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/js/jquery.blockUI.js"></script>
<script src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/js/waves.js"></script>
<script src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/js/jquery.slimscroll.js"></script>
<script src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/js/jquery.scrollTo.min.js"></script>
<script src="../plugins/switchery/switchery.min.js"></script>

<!-- App js -->
<script src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/js/jquery.core.js"></script>
<script src="<?php echo $this->basePath(); ?>/themes/ucpanel/theme/assets/js/jquery.app.js"></script>

</body>
</html>