<?php $this->headTitle($pageTitle); ?>
<div class="container box">
    <table class="table table-hover table-striped no-margin">

        <tbody>
        <tr>
            <td><?= __('Amount') ?>:</td>
            <td><?=currentCurrency()->country->symbol_left?><?php echo number_format($invoice->amount,2);?></td>


        </tr>

        <tr>
            <td><?= __('Amount') ?>:</td>
            <td><?= __('Enrollment for') ?> <?= __('course-session') ?></td>

        </tr>


        <tr>
            <td>&nbsp;</td>
            <td>



                <div class="buttons">
                    <div class="right">

                        <?php if ($sandbox) { ?>
                            <div class="warning" style="color: red"><?= __('payfast-warning') ?> </div>
                        <?php } ?>
                        <form action="<?php echo $action; ?>" method="post">
                            <input type="hidden" name="merchant_id" value="<?php echo $merchant_id; ?>" />
                            <input type="hidden" name="merchant_key" value="<?php echo $merchant_key; ?>" />
                            <input type="hidden" name="amount" value="<?php echo $amount; ?>" />
                            <input type="hidden" name="item_name" value="<?php echo $item_name; ?>" />
                            <input type="hidden" name="item_description" value="<?php echo $item_description; ?>" />
                            <input type="hidden" name="name_first" value="<?php echo $name_first; ?>" />
                            <input type="hidden" name="name_last" value="<?php echo $name_last; ?>" />
                            <input type="hidden" name="email_address" value="<?php echo $email_address; ?>" />
                            <input type="hidden" name="return_url" value="<?php echo $return_url; ?>" />
                            <input type="hidden" name="notify_url" value="<?php echo $notify_url; ?>" />
                            <input type="hidden" name="cancel_url" value="<?php echo $cancel_url; ?>" />
                            <input type="hidden" name="custom_str1" value="<?php echo $custom_str1; ?>" />
                            <input type="hidden" name="m_payment_id" value="<?php echo $m_payment_id; ?>" />
                            <input type="hidden" name="signature" value="<?php echo $signature; ?>" />
                            <div class="buttons">
                                <div class="right">
                                    <input type="submit" value="<?= __('pay-now') ?>" class="btn btn-primary" />
                                </div>
                            </div>
                        </form>

                    </div>
                </div>










            </td>

        </tr>


        </tbody>
    </table>


</div>