<?php $this->headTitle($pageTitle); ?>
<div class="container box">
    <table class="table table-hover table-striped no-margin">

        <tbody>
        <tr>
            <td><?= __('Amount') ?>:</td>
            <td><?=currentCurrency()->country->symbol_left?><?php echo number_format($invoice->amount,2);?></td>

        </tr>

        <tr>
            <td><?= __('Description') ?>:</td>
            <td><?= __('Enrollment for') ?> <?php echo 'Course/Session'; ?></td>

        </tr>

        <tr>
            <td><?= __('Transaction ID') ?>:</td>
            <td><?php echo $tid?></td>

        </tr>

        <tr>
            <td>&nbsp;</td>
            <td>

                <form>
                    <a class="flwpug_getpaid"
                       data-PBFPubKey="<?=$pkey?>"
                       data-txref="<?=$tid?>"
                       data-amount="<?=$invoice->amount?>"
                       data-customer_email="<?=$student->email?>"
                       data-customer_phonenumber="<?=$student->mobile_number?>"
                       data-currency="<?=strtoupper($country->currency_code) ?>"
                       data-country="<?=strtoupper($country->iso_code_2) ?>"
                       data-redirect_url="<?=$this->url('application/default',['controller'=>'callback','action'=>'rave'],['force_canonical' => true])?>"></a>

                    <?php if($mode==0): ?>
                    <script type="text/javascript" src="https://ravesandboxapi.flutterwave.com/flwv3-pug/getpaidx/api/flwpbf-inline.js"></script>
                    <?php else: ?>
                    <script type="text/javascript" src="https://api.ravepay.co/flwv3-pug/getpaidx/api/flwpbf-inline.js"></script>
                    <?php endif; ?>
                </form>






            </td>

        </tr>


        </tbody>
    </table>


</div>