<div class="row">
			<div >
				<div class="box">
					 
					<div class="box-body">
						               <?php  
$form->prepare();
$form->setAttribute('action', $this->url('admin/default',array('controller'=>'download','action'=>$action,'id'=>$id)));
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');  
$form->setAttribute('class', 'form-horizontal');     

echo $this->form()->openTag($form);   
?> 
                          
                                                
                                  
							 
									<div class="form-group"> 
											<?php     echo $this->formLabel($form->get('download_name'));
   
?>
										 <?php     echo $this->formElement($form->get('download_name'));
   
?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('download_name'));?></p>
									 
									</div>



							 
						 	<div class="form-group"> 
											<?php     echo $this->formLabel($form->get('description'));
   
?>
										 <?php     echo $this->formElement($form->get('description'));
   
?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('description'));?></p>
									 
									</div>

                        <div class="form-group">
                            <?php     echo $this->formLabel($form->get('status'));

                            ?>
                            <?php     echo $this->formElement($form->get('status'));

                            ?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('status'));?></p>

                        </div>

                                                
                                                
                                                
                   
                                                
                                                
                                                
							 
							<div class="form-footer">
								<button type="submit" class="btn btn-primary"><?= __('save') ?></button>
							</div>
						<?php echo $this->form()->closeTag($form);  ?>
					</div>
				</div><!--end .box -->
			</div><!--end .col-lg-12 -->
		</div>
<?php $this->headScript()->prependFile($this->basePath() . '/ckeditor/ckeditor.js')
     ?>
 <script type="text/javascript">
 
CKEDITOR.replace('hcontent', {
	filebrowserBrowseUrl: '<?php echo $this->basepath() ?>/admin/filemanager',
	filebrowserImageBrowseUrl: '<?php echo $this->basepath() ?>/admin/filemanager',
	filebrowserFlashBrowseUrl: '<?php echo $this->basepath() ?>/admin/filemanager'
});
 
</script> 
