<div class="row">
			<div >
				<div class="box">
					 
					<div class="box-body">
						               <?php  
$form->prepare();
$form->setAttribute('action', $this->url('admin/default',array('controller'=>'news','action'=>$action,'id'=>$id)));
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');  
$form->setAttribute('class', 'form-horizontal');     

echo $this->form()->openTag($form);   
?> 
                          
                                                
                                  
							 
									<div class="form-group"> 
											<?php     echo $this->formLabel($form->get('title'));
   
?>
										 <?php     echo $this->formElement($form->get('title'));
   
?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('title'));?></p>
									 
									</div>
								 
                                
                                
							 
						 	<div class="form-group"> 
											<?php     echo $this->formLabel($form->get('content'));
   
?>
										 <?php     echo $this->formElement($form->get('content'));
   
?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('content'));?></p>
									 
									</div>
								 
                                	 
    <div class="form-group" style="margin-bottom:10px">
								 
									<label for="image" class="control-label"><?= __('Cover Image') ?></label><br />
							 
									
                               <div class="image"><img data-name="image" src="<?php echo $display_image ?>" alt="" id="thumb" /><br />
                  <?php echo $this->formElement($form->get('picture')) ?>
                  <a class="pointer" onclick="image_upload('image', 'thumb');"><?=__('browse')?></a>&nbsp;&nbsp;|&nbsp;&nbsp;<a class="pointer" onclick="$('#thumb').attr('src', '<?php echo $no_image; ?>'); $('#image').attr('value', '');"><?= __('clear') ?></a></div>
                    <div><small><?= __('recommended') ?>: 1170px X 711px</small></div>
</div>                                
                                
                                
                            
                             
                                                
                                                
                                                
                   
                                                
                                                
                                                
							 
							<div class="form-footer">
								<button type="submit" class="btn btn-primary"><?=__('save-changes')?></button>
							</div>
						<?php echo $this->form()->closeTag($form);  ?>
					</div>
				</div><!--end .box -->
			</div><!--end .col-lg-12 -->
		</div>
<?php $this->headScript()->prependFile($this->basePath() . '/ckeditor/ckeditor.js')
     ?>
 <script type="text/javascript">
 
CKEDITOR.replace('hcontent', {
	filebrowserBrowseUrl: '<?php echo $this->basepath() ?>/admin/filemanager',
	filebrowserImageBrowseUrl: '<?php echo $this->basepath() ?>/admin/filemanager',
	filebrowserFlashBrowseUrl: '<?php echo $this->basepath() ?>/admin/filemanager'
});
 
</script> 
<script type="text/javascript"><!--
function image_upload(field, thumb) {
	$('#dialog').remove();
	
	$('#content').prepend('<div id="dialog" style="padding: 3px 0px 0px 0px;"><iframe src="<?php echo $this->basePath(); ?>/admin/filemanager?&token=true&field=' + encodeURIComponent(field) + '" style="padding:0; margin: 0; display: block; width: 100%; height: 100%;" frameborder="no" scrolling="auto"></iframe></div>');
	
	$('#dialog').dialog({
		title: '<?=__('image-manager')?>',
		close: function (event, ui) {
			if ($('#' + field).attr('value')) {
				$.ajax({
					url: '<?php echo $this->basePath(); ?>/admin/filemanager/image?&image=' + encodeURIComponent($('#' + field).val()),
					dataType: 'text',
					success: function(data) {
						$('#' + thumb).replaceWith('<img src="' + data + '" alt="" id="' + thumb + '" />');
					}
				});
			}
		},	
		bgiframe: false,
		width: 800,
		height: 570,
		resizable: true,
		modal: false
	});
};
//--></script> 		