<?php $this->headTitle(__('blog').' - '.$row->title)?>



<?php $this->headStyle()->captureStart() ?>
section.page-title {
display:none;
}
<?php $this->headStyle()->captureEnd() ?>


<section class="grey section">
    <div class="container">
        <div class="row">
            <div id="content" class="col-md-12 col-sm-12 col-xs-12">
                <div class="blog-wrapper">
                    <div class="row second-bread">
                        <div class="col-md-6 text-left">
                            <h1><?php echo $this->getSetting('label_blog',__('Blog'))?></h1>
                        </div>
                        <div class="col-md-6 text-right">
                            <div class="bread">
                                <ol class="breadcrumb">
                                    <li><a href="<?php echo $this->basePath() ?>/"><?= __('Home') ?></a></li>
                                    <li><a href="<?php echo $this->url('news') ?>"><?php echo $this->getSetting('label_blog',__('Blog'))?></a></li>
                                    <li class="active"><?= __('Post') ?></li>

                                </ol>
                            </div>
                        </div>
                    </div>
                </div>


                    <div class="blog-wrapper">
                        <div class="blog-title">
                            <h2><a href="<?php echo $this->url('news-entry',array('id'=>$row->newsflash_id));?>" title=""><?php echo $row->title; ?></a></h2>
                            <div class="post-meta">
<span>
<i class="fa fa-calendar"></i>
<a href="#"><?php echo date('d/M/Y',$row->date)?></a>
</span>
                            </div>
                        </div>
                        <?php if(!empty($row->picture)):?>
                            <div class="blog-image">
                                <a href="<?php echo $this->url('news-entry',array('id'=>$row->newsflash_id));?>" title=""><img src="<?php echo resizeImage($row->picture, 1000, 579, $this->basePath());?>" alt="" class="img-responsive"></a>
                            </div>
                        <?php endif; ?>
                        <div class="blog-desc" style="min-height: 300px">
                            <div class="post-date">
                                <span class="day"><?php echo date('d',$row->date)?></span>
                                <span class="month"><?php echo date('M',$row->date)?></span>
                            </div>
                            <p><?php echo $row->content ?></p>

                        </div>
                    </div>

                <hr class="invis">
                <div>
                <?php $shortName = $this->getSetting('general_disqus'); if(!empty($shortName)):?>
                    <script type="text/javascript">
                        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
                        var disqus_shortname = '<?php echo trim($shortName); ?>'; // required: replace example with your forum shortname

                        /* * * DON'T EDIT BELOW THIS LINE * * */
                        (function () {
                            var s = document.createElement('script'); s.async = true;
                            s.type = 'text/javascript';
                            s.src = '//' + disqus_shortname + '.disqus.com/count.js';
                            (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
                        }());
                    </script>
                <?php endif; ?>
                </div>

            </div>

        </div>
    </div>
</section>