<?php  $this->headTitle($pageTitle) ?>


<!--container starts-->
<div >
    <!--primary starts-->

    <div class="box-body">

        <form id="filterform" class="form-inline" role="form"  method="get" action="<?=$this->url('admin/default',['controller'=>'forum','action'=>'index'])?>">


            <div class="form-group" style="min-width: 200px">
                <label class="sr-only" for="session_id"><?= __('session-course') ?></label>
                <?php echo $this->formElement($select) ?>
            </div>

            <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> <?= __('filter') ?></button>

        </form>


        <div class="btn-group pull-right">

            <a class="btn btn-primary" href="<?=$this->url('admin/default',['controller'=>'forum','action'=>'addtopic'])?>"><i class="fa fa-plus"> <?= __('add-topic') ?></i></a>

        </div>








        <div class="table-responsive_">
            <table class="table table-hover table-striped">
                <thead>
                <tr>
                    <th><?= __('Topic') ?></th>
                    <th><?= __('Session/Course') ?></th>
                    <th><?= __('Created By') ?></th>
                    <th><?= __('Added On') ?></th>
                    <th ><?= __('Replies') ?></th>
                    <th><?= __('Last Reply') ?></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($topics as $row): ?>
                    <?php $topic = \Application\Entity\ForumTopic::find($row->forum_topic_id); ?>
                    <tr>
                        <td><?php echo $row->topic_title; ?></td>
                        <td><?=$row->session_name?></td>
                        <td>
                            <?php  echo forumUser($row->topic_owner,$row->topic_owner_type)['name'] ?>
                        </td>
                        <td><?=date('d/M/Y',$row->created_on)?></td>
                        <td><?=($topic->forumPosts->count()-1) ?></td>
                        <td><?php if($topic->forumPosts->count()-1 > 0):?>
                                <?=date('D, d M Y g:i a',$topic->forumPosts()->orderBy('forum_post_id','desc')->first()->post_created_on); ?>
                            <?php endif; ?>
                        </td>
                        <td class="text-right">
                            <a class="btn btn-primary" href="<?=$this->url('admin/default',['controller'=>'forum','action'=>'topic','id'=>$row->forum_topic_id])?>"><?= __('View') ?></a>

                            <a onclick="return confirm('Are you sure you want to delete this topic and all its posts?')" class="btn btn-danger" href="<?php echo  $this->url('admin/default',['controller'=>'forum','action'=>'deletetopic','id'=>$row->forum_topic_id]) ?>"><?= __('Delete Topic') ?></a>

                        </td>
                    </tr>

                <?php endforeach; ?>

                </tbody>
            </table>
        </div>
        <?php 
        // add at the end of the file after the table
        echo $this->paginationControl(
        // the paginator object
            $topics,
            // the scrolling style
            'sliding',
            // the partial to use to render the control
            array('partial/paginator.phtml', 'Admin'),
            // the route to link to when a user clicks a control link
            array(
                'route' => 'admin/default',
                'controller'=>'forum',
                'action'=>'index'
            )
        );
        
        ?>
    </div>


</div>

<!--container ends-->
