<?php $this->headScript()->appendFile($this->basePath().'/js/angular.min.js')
    ->appendFile($this->basePath().'/app/attendance.js')?>
<div   ng-app="myApp" ng-controller="myCtrl" class="row">
			<div >
				<div class="box">

					<div class="box-body">
						               <?php  
$form->prepare();
$form->setAttribute('action', $this->url('admin/default',array('controller'=>'homework','action'=>$action,'id'=>$id)));
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');  
$form->setAttribute('class', 'form-horizontal');     

echo $this->form()->openTag($form);   
?> 
                          
                                                
                                  
							 
									<div class="form-group"> 
											<?php     echo $this->formLabel($form->get('title'));
   
?>
										 <?php     echo $this->formElement($form->get('title'));
   
?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('title'));?></p>
									 
									</div>
														<div class="form-group"> 
											<?php     echo $this->formLabel($form->get('session_id'));
   
?>
										 <?php     echo $this->formElement($form->get('session_id'));
   
?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('session_id'));?></p>
									 
									</div>

                        <div class="form-group">
                            <?php     echo $this->formLabel($form->get('lesson_id'));

                            ?>
                            <?php     echo $this->formElement($form->get('lesson_id'));

                            ?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('lesson_id'));?></p>

                        </div>


                        <div class="form-group">
											<?php     echo $this->formLabel($form->get('description'));
   
?>
										 <?php     echo $this->formElement($form->get('description'));
   
?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('description'));?></p>
									 
									</div>
				   
                                
							 
						 	<div class="form-group"> 
											<?php     echo $this->formLabel($form->get('content'));
   
?>
										 <?php     echo $this->formElement($form->get('content'));
   
?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('content'));?></p>
									 
									</div>
								 

                        <div class="form-group">
                            <input checked type="checkbox" name="notify" value="1"/> <?= __('notify-session-students') ?>?
                        </div>
								 
 
                                                
							 
							<div class="form-footer">
								<button type="submit" class="btn btn-primary"><?= __('save-changes') ?></button> 
							</div>
						<?php echo $this->form()->closeTag($form);  ?>
					</div>
				</div><!--end .box -->
			</div><!--end .col-lg-12 -->
		</div>
<?php $this->headScript()->prependFile($this->basePath() . '/ckeditor/ckeditor.js')
     ?>
 <script type="text/javascript">
 
CKEDITOR.replace('hcontent', {
	filebrowserBrowseUrl: '<?php echo $this->basepath() ?>/admin/filemanager',
	filebrowserImageBrowseUrl: '<?php echo $this->basepath() ?>/admin/filemanager',
	filebrowserFlashBrowseUrl: '<?php echo $this->basepath() ?>/admin/filemanager'
});
 
</script>

<script>
    var basePath = '<?php echo $this->basePath() ?>';
</script>