<form class="form" action="<?php echo selfURL() ?>" method="post">

    <div class="form-group">
        <?php     echo $this->formLabel($form->get('session_id')); ?>
        <?php echo $this->formElement($form->get('session_id')) ?>
        <p class="help-block"><?php echo $this->formElementErrors($form->get('session_id'));?></p>
    </div>


    <div class="form-group">
        <?php     echo $this->formLabel($form->get('opening_date')); ?>
        <?php echo $this->formElement($form->get('opening_date')) ?>
        <p class="help-block"><?php echo $this->formElementErrors($form->get('opening_date'));?></p>
    </div>



    <div class="form-group">
        <?php     echo $this->formLabel($form->get('closing_date')); ?>
        <?php echo $this->formElement($form->get('closing_date')) ?>
        <p class="help-block"><?php echo $this->formElementErrors($form->get('closing_date'));?></p>
    </div>




    <div class="form-footer">
        <button type="submit" class="btn btn-primary"><?=__('save')?></button>
    </div>
</form>

<?php echo $this->headLink()->prependStylesheet($this->basePath().'/pickadate/themes/default.date.css')
    ->prependStylesheet($this->basePath().'/pickadate/themes/default.time.css')
    ->prependStylesheet($this->basePath().'/pickadate/themes/default.css') ;?>
<script type="text/javascript" src="<?php echo $this->basePath() ?>/pickadate/picker.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath() ?>/pickadate/picker.date.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath() ?>/pickadate/picker.time.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath() ?>/pickadate/legacy.js"></script>
<script>
    $(function(){
        $('.date').pickadate({
            format: 'yyyy-mm-dd'
        });
    });
</script>