<form action="<?php echo $this->url('admin/default',['controller'=>'test','action'=>'editoption','id'=>$id]);?>" method="post">
    <div class="form-group">
        <label for="option"><?= __('option') ?></label>
        <?php echo $this->formElement($option) ?>
    </div>
    <div class="form-group">
        <label for="is_correct"><?= __('is-correct-option') ?></label>
        <?php echo $this->formElement($select) ?>
    </div>
    <button class="btn btn-primary btn-block" type="submit"><?=__('save')?></button>
</form>