<div class="row">
    <div >
        <div class="box">

            <div class="box-body">
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th><?= __('title') ?></th>
                        <th><?= __('session-course') ?></th>
                        <th><?= __('created-on') ?></th>
                        <th><?= __('due-date') ?></th>
                        <th class="text-right1" ></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($paginator as $row): ?>
                        <tr>
                            <td><?php echo $row->title; ?></td>
                            <td><span ><?php echo $row->session_name ?></span></td>
                            <td><?php echo date('d/M/Y',$row->created_on); ?></td>
                            <td><?php echo date('d/M/Y',$row->due_date); ?></td>

                            <td class="text-right1">
                                <a class="btn btn-primary" href="<?php echo $this->url('application/submit-assignment',['id'=>$row->assignment_id]); ?>"><i class="fa fa-file"></i> <?= __('submit-homework') ?></a>
                            </td>
                        </tr>
                        <tr>
                            <td class="readmorebox" colspan="5">

                                <article class="readmore">
                                    <?php echo $row->instruction ?>
                                </article>
                            </td>
                        </tr>
                    <?php endforeach; ?>

                    </tbody>
                </table>

                <?php
                // add at the end of the file after the table
                echo $this->paginationControl(
                // the paginator object
                    $this->paginator,
                    // the scrolling style
                    'sliding',
                    // the partial to use to render the control
                    array('partial/paginator.phtml', 'Applications'),
                    // the route to link to when a user clicks a control link
                    array(
                        'route' => 'application/assignments',
                    )
                );
                ?>
            </div><!--end .box-body -->
        </div><!--end .box -->
    </div><!--end .col-lg-12 -->
</div>
<?php $this->headScript()->prependFile($this->basePath() . '/static/readmore/readmore.min.js')
?>
<script>
    $(function(){
        $('article.readmore').readmore({
            collapsedHeight : 200
        });
    });
</script>

<!-- START SIMPLE MODAL MARKUP --><!-- /.modal -->
<!-- END SIMPLE MODAL MARKUP -->
