<?php  $this->headTitle($pageTitle) ?>
<div>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab"><i class="fa fa-info-circle"></i> <?= __('introduction') ?></a></li>
        <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab"><i class="fa fa-table"></i> <?= __('table-of-contents') ?></a></li>
        <li role="presentation"><a href="#resources" aria-controls="resources" role="tab" data-toggle="tab"><i class="fa fa-download"></i> <?= __('resources') ?></a></li>

    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="home">

            <div class="panel panel-default">
                <div class="panel-body">
                    <p><?php echo $classRow->introduction ?></p>
                </div>
                <div class="panel-footer" style="min-height: 65px">
                    <?php if($previous): ?>
                        <a class="btn btn-primary btn-lg" href="<?php echo $previous ?>"><i class="fa fa-chevron-circle-left"></i> <?= __('previous') ?></a>
                    <?php endif; ?>

                    <?php if($next): ?>
                    <a class="btn btn-primary btn-lg pull-right" href="<?php echo $next ?>"><?= __('start-class') ?> <i class="fa fa-chevron-circle-right"></i></a>
                    <?php endif; ?>
                </div>
            </div>

        </div>
        <div role="tabpanel" class="tab-pane" id="profile">
            <?php $count=1; foreach($lectures as $row): ?>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <?php echo $count.'. '.$row->lecture_title ?>
                    </div>
                    <div class="panel-body">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th><?= __('content') ?></th>
                                <th><?= __('type') ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach($lecturePageTable->getPaginatedRecords(false,$row->lecture_id) as $page): ?>
                                <tr>
                                    <td><?php echo $page->title ?></td>
                                    <td><?php
                                        switch($page->type){
                                            case 't':
                                                echo __('text');
                                                break;
                                            case 'v':
                                                echo  __('video');
                                                break;
                                            case 'c':
                                                echo __('html-code');
                                                break;
                                            case 'i':
                                                echo __('image');
                                                break;
                                            case 'q':
                                                echo __('quiz');
                                                break;
                                            case 'l':
                                                echo  __('video');
                                                break;
                                        } ?></td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="panel-footer" style="min-height: 65px">
                        <a class="btn btn-primary btn-lg pull-right" href="<?php echo $this->url('view-lecture',['sessionId'=>$sessionId,'lectureId'=>$row->lecture_id]) ?>"><?= __('start-lecture') ?> <i class="fa fa-chevron-right"></i></a>
                    </div>
                </div>
                <?php $count++; ?>
            <?php endforeach; ?>
        </div>
        <div role="tabpanel" class="tab-pane" id="resources">
          <?php if($downloads->count() > 0):?>
            <a href="<?php echo $this->url('class-files',array('id'=>$classRow->lesson_id,'sessionId'=>$sessionId));?>" class="btn btn-primary" data-toggle="tooltip" data-placement="top" data-original-title="<?= __('download-all') ?> <?= __('files') ?>"><i class="fa fa-download"></i> <?= __('download-all') ?></a>
          <?php endif; ?>
            <table class="table table-hover">
                <thead>
                <tr>
                    <th><?= __('file') ?></th>
                    <th ></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($downloads as $download): ?>
                        <td><?php echo basename($download->path); ?></td>

                        <td class="text-right">
                        <?php if ($fileTable->getTotalForDownload($classRow->lesson_id)> 0): ?>
                    <a href="<?php echo $this->url('class-file',array('id'=>$download->lesson_file_id,'sessionId'=>$sessionId));?>" class="btn btn-primary" data-toggle="tooltip" data-placement="top" data-original-title="<?= __('download') ?> <?= __('file') ?>"><i class="fa fa-download"></i> <?= __('download') ?></a>

                <?php else:?>
                    <strong><?= __('no-files-available') ?></strong>
                <?php endif; ?>
                        </td>
                    </tr>

            <?php endforeach; ?>

                </tbody>
            </table>

        </div>
        <div role="tabpanel" class="tab-pane" id="progress">

        </div>
        <?php if(!empty($sessionRow->enable_discussion)):?>
            <div role="tabpanel" class="tab-pane" id="discuss">
                <form class="form" method="post" action="<?php echo $this->url('application/default',['controller'=>'student','action'=>'adddiscussion']); ?>">

                    <p><?= __('ask-a-question') ?></p>
                    <div class="modal-body">

                        <?php echo $this->formElement($form->get('security')); ?>
                        <div class="form-group">
                            <label>Recipients</label>
                            <select name="account_id[]" class="form-control select2" data-options="required:true" required="required" multiple="multiple"><option value=""></option>
                                <option value="admins"><?= __('administrators') ?></option>
                                <?php foreach($instructors as $instructor):?>
                                    <option value="<?php echo $instructor->account_id ?>"><?php echo $instructor->first_name.' '.$instructor->last_name; ?></option>
                                <?php endforeach; ?>

                            </select>
                        </div>

                        <input type="hidden" name="session_id" value="<?php echo $sessionId ?>"/>
                        <div class="form-group">
                            <?php     echo $this->formLabel($form->get('subject'));

                            ?>
                            <?php     echo $this->formElement($form->get('subject'));

                            ?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('subject'));?></p>

                        </div>




                        <div class="form-group">
                            <?php     echo $this->formLabel($form->get('question'));

                            ?>
                            <?php     echo $this->formElement($form->get('question'));

                            ?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('question'));?></p>

                        </div>

                        <button type="submit" class="btn btn-primary"><?= __('submit') ?></button>

                    </div>

                </form>
                <div class="row">
                    <div class="col-md-12" style="margin-top: 20px">
                        <h2><?= __('your-questions') ?></h2>
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th><?= __('subject') ?></th>
                                <th><?= __('created-on') ?></th>
                                <th><?= __('recipients') ?></th>
                                <th><?= __('replied') ?></th>
                                <th class="text-right1" style="width:90px"></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach($discussions as $row): ?>
                                <tr>
                                    <td><?php echo $row->subject; ?>
                                    </td>

                                    <td><?php echo date('d/M/Y',$row->created_on); ?></td>
                                    <td>

                                        <?php if($row->admin==1):?>
                                            <?= __('administrators') ?>,
                                        <?php endif; ?>

                                        <?php foreach($accountTable->getDiscussionAccounts($row->discussion_id) as $row2): ?>
                                            <?php echo $row2->first_name.' '.$row2->last_name; ?>,
                                        <?php endforeach; ?>



                                    </td>

                                    <td><?php echo boolToString($row->replied) ?></td>

                                    <td class="text-right">
                                        <a href="<?php echo $this->url('application/viewdiscussion',array('id'=>$row->discussion_id));?>" class="btn btn-primary" data-toggle="tooltip" data-placement="top" data-original-title="View"><i class="fa fa-eye"></i> <?= __('view') ?></a>

                                    </td>
                                </tr>
                            <?php endforeach; ?>

                            </tbody>
                        </table>


                    </div>

                </div>

            </div>
        <?php endif; ?>

    </div>

</div>