<div class="form-group" style="padding-bottom: 10px">
    <label><?= __('list-type') ?>:</label>
    <select id="type" class="form-control" name="type">
        <option value="classes"><?= __('specific-classes') ?></option>
        <option value="minimum"><?= __('minimum-no-classes') ?></option>
    </select>

</div>

<div class="option classes">
<?php foreach($lessons as $row): ?>
    <div  class="form-group" style="padding-bottom: 10px">
        <input checked type="checkbox" name="lesson_<?php echo $row->lesson_id?>" value="<?php echo $row->lesson_id?>"/> <label for="session_id">Class <?php echo $row->lesson_id?>: <?php echo $row->lesson_name?> </label>

    </div>
<?php endforeach; ?>

</div>
<div class="option minimum form-group">
    <label>
        <?= __('enter-minimum-no-classes') ?>
    </label>
    <input  class="form-control" type="text" name="quantity" placeholder="<?= __('digits-only') ?>"/>

</div>