<div class="box">
    <div class="box-body">
        <div>

            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#import" aria-controls="import" role="tab" data-toggle="tab"><?= __('import') ?></a></li>
                <li role="presentation"><a href="#export" aria-controls="export" role="tab" data-toggle="tab"><?= __('export') ?></a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="import">

                    <form onsubmit="return confirm('<?=__('import-students-confirm')?>')" enctype="multipart/form-data" class="form" method="post" action="<?php echo $this->url('admin/default',array('controller'=>'student','action'=>'import')); ?>">
                        <h2><?= __('import-new-students') ?></h2>
                        <p>
                            <?= __('import-students-help',['link'=> $this->url('admin/default',array('controller'=>'student','action'=>'csvsample'))]) ?>
                          </p>





                        <div class="form-group" style="padding-bottom: 10px">
                            <label for="file"><?= __('csv-file') ?></label>
                            <input required="required" name="file" type="file"/>
                        </div>

                        <button class="btn btn-primary" type="submit"><?= __('import') ?></button>
                    </form>

                </div>
                <div role="tabpanel" class="tab-pane" id="export">

                    <p>
                        <?= __('export-all-students') ?>
                    </p>
                    <p>
                        <a class="btn btn-primary " href="<?php echo $this->url('admin/default',['controller'=>'student','action'=>'exportstudents']) ?>"><?= __('export') ?></a>
                    </p>

                </div>
            </div>

        </div>
    </div>
</div>