<form id="manageform" action="<?php echo $this->url('admin/default',['controller'=>'student','action'=>'manageinstructors','id'=>$id]);?>" method="post" >
<div style="max-height: 400px; overflow: auto">

<table id="datatable" class="table table-stripped">
    <thead>
    <tr>
        <th></th>
        <th><?= __('name') ?></th>
        <th><?= __('role') ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($rowset as $row):?>
    <tr>
        <td><input <?php if($table->accountExists($slrow->lesson_id,$slrow->session_id,$row->account_id)):?> checked="checked" <?php endif; ?> name="<?php echo $row->account_id ?>" value="<?php echo $row->account_id; ?>" type="checkbox"/></td>
        <td><?php echo $row->first_name.' '.$row->last_name?></td>
        <td><?php echo $row->role; ?></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>

</div>
<button type="button" id="savebtn" class="btn btn-primary pull-right"><?=__('save')?></button>
</form>
<div style="clear: both"></div>