<form onsubmit="return confirm('You are about to enroll students. Continue?')" enctype="multipart/form-data" class="form" method="post" action="<?php echo $this->url('admin/default',array('controller'=>'student','action'=>'massenroll')); ?>">
    <h2><?= __('enroll-multiple-to-course') ?></h2>
    <p>
        <?= __('enroll-multiple-help',['link'=>$this->url('admin/default',array('controller'=>'student','action'=>'csvsample'))]) ?>
    </p>

    <div class="form-group" style="padding-bottom: 10px">
       <label for="session_id"><?= __('session-course') ?></label>
            <?php echo $this->formElement($select) ?>
    </div>



    <div class="form-group" style="padding-bottom: 10px">
        <label for="file"><?= __('csv-file') ?></label>
        <input required="required" name="file" type="file"/>
    </div>

    <button class="btn btn-primary" type="submit"><?= __('enroll') ?></button>
</form>