<div class="row">
			<div >
				<div class="box">
					 
					<div class="box-body">
						               <?php  
$form->prepare();
$form->setAttribute('action', $this->url('admin/default',array('controller'=>'certificate','action'=>$action,'id'=>$id)));
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');  
$form->setAttribute('class', 'form-horizontal');     

echo $this->form()->openTag($form);   
?> 
                          
                                                
                                  
							 
									<div class="form-group"> 
											<?php     echo $this->formLabel($form->get('certificate_name'));
   
?>
										 <?php     echo $this->formElement($form->get('certificate_name'));
   
?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('certificate_name'));?></p>
									 
									</div>


                        <div class="form-group">
                            <?php     echo $this->formLabel($form->get('session_id'));

                            ?>
                            <?php     echo $this->formElement($form->get('session_id'));

                            ?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('session_id'));?></p>

                        </div>
							 
						 	<div class="form-group"> 
											<?php     echo $this->formLabel($form->get('description'));
   
?>
										 <?php     echo $this->formElement($form->get('description'));
   
?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('description'));?></p>
									 
									</div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <?php     echo $this->formLabel($form->get('status'));

                                    ?>
                                    <?php     echo $this->formElement($form->get('status'));

                                    ?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('status'));?></p>

                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <?php     echo $this->formLabel($form->get('orientation'));

                                    ?>
                                    <?php     echo $this->formElement($form->get('orientation'));

                                    ?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('orientation'));?></p>

                                </div>


                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <?php     echo $this->formLabel($form->get('max_downloads'));

                                    ?>
                                    <?php     echo $this->formElement($form->get('max_downloads'));

                                    ?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('max_downloads'));?></p>
                                    <p class="help-block"><?= __('download-help') ?></p>
                                </div>
                            </div>

                        </div>






                        <div class="form-group" style="margin-bottom:10px">
								 
									<label for="image" class="control-label"><?= __('certificate-image') ?>(A4 <?= __('size') ?> - 595 <?= __('pixels') ?> x 842 <?= __('pixels') ?>)</label><br />
							 
									
                               <div class="image"><img data-name="image" src="<?php echo $display_image ?>" alt="" id="thumb" /><br />
                  <?php echo $this->formElement($form->get('certificate_image')) ?>
                  <a class="pointer" onclick="image_upload('image', 'thumb');"><?= __('browse') ?></a>&nbsp;&nbsp;|&nbsp;&nbsp;<a class="pointer" onclick="$('#thumb').attr('src', '<?php echo $no_image; ?>'); $('#image').attr('value', '');"><?= __('clear') ?></a></div>

</div>                                
                                
                                
                            
                             
                                                
                                                
                                                
                   
                                                
                                                
                                                
							 
							<div class="form-footer">
								<button type="submit" class="btn btn-primary"><?= __('save') ?></button>
							</div>
						<?php echo $this->form()->closeTag($form);  ?>
					</div>
				</div><!--end .box -->
			</div><!--end .col-lg-12 -->
		</div>
<?php $this->headScript()->prependFile($this->basePath() . '/ckeditor/ckeditor.js')
     ?>
 <script type="text/javascript">
 
CKEDITOR.replace('hcontent', {
	filebrowserBrowseUrl: '<?php echo $this->basepath() ?>/admin/filemanager',
	filebrowserImageBrowseUrl: '<?php echo $this->basepath() ?>/admin/filemanager',
	filebrowserFlashBrowseUrl: '<?php echo $this->basepath() ?>/admin/filemanager'
});
 
</script> 
<script type="text/javascript">
function image_upload(field, thumb) {
    console.log('clicled');
	$('#dialog').remove();
	
	$('#content').prepend('<div id="dialog" style="padding: 3px 0px 0px 0px;"><iframe src="<?php echo $this->basePath(); ?>/admin/filemanager?&token=true&field=' + encodeURIComponent(field) + '" style="padding:0; margin: 0; display: block; width: 100%; height: 100%;" frameborder="no" scrolling="auto"></iframe></div>');
	
	$('#dialog').dialog({
		title: '<?=__('Image Manager')?>',
		close: function (event, ui) {
			if ($('#' + field).attr('value')) {
				$.ajax({
					url: '<?php echo $this->basePath(); ?>/admin/filemanager/image?&image=' + encodeURIComponent($('#' + field).val()),
					dataType: 'text',
					success: function(data) {
						$('#' + thumb).replaceWith('<img src="' + data + '" alt="" id="' + thumb + '" />');
					}
				});
			}
		},	
		bgiframe: false,
		width: 800,
		height: 570,
		resizable: true,
		modal: false
	});
};
</script>