<div class="row">
    <div >
        <div class="box">
            <div class="box-head">
                <header></header>
                <a class="btn btn-primary pull-right" href="<?php echo $this->url('admin/default',array('controller'=>'certificate','action'=>'add')) ?>"><i class="fa fa-plus"></i> <?= __('Create Certificate') ?></a>



            </div>
            <div class="box-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th><?= __('name') ?></th>
                        <th><?= __('session-course') ?></th>
                        <th><?= __('enabled') ?></th>
                        <th><?= __('student-downloads') ?></th>
                        <?php if(GLOBAL_ACCESS):?>
                        <th><?= __('created-by') ?></th>
                        <?php endif; ?>
                        <th class="text-right1" ><?= __('actions') ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($paginator as $row): ?>
                        <tr>
                            <td><span class="label label-success"><?php echo $row->certificate_id ?></span></td>
                            <td><?php echo $row->certificate_name; ?></td>
                            <td><?php echo $row->session_name; ?></td>
                            <td><?php echo boolToString($row->status); ?></td>
                            <td>
                                <a href="<?=$this->url('admin/default',['controller'=>'certificate','action'=>'students','id'=>$row->certificate_id])?>"> <?=\Application\Entity\Certificate::find($row->certificate_id)->studentCertificates()->count();?></a>
                            </td>
                            <?php if(GLOBAL_ACCESS):?>
                                <td><?php echo $this->adminName($row->account_id) ?></td>
                            <?php endif; ?>

                            <td class="text-right1">
                                <a href="<?php echo $this->url('admin/default',array('controller'=>'certificate','action'=>'edit','id'=>$row->certificate_id));?>" class="btn btn-xs btn-default btn-equal" data-toggle="tooltip" data-placement="top" data-original-title="<?=__('edit')?>"><i class="fa fa-pencil"></i></a>

                                <a onclick="return confirm('<?=__('delete-confirm')?>')" href="<?php echo $this->url('admin/default',array('controller'=>'certificate','action'=>'delete','id'=>$row->certificate_id));?>"  class="btn btn-xs btn-default btn-equal" data-toggle="tooltip" data-placement="top" data-original-title="<?=__('delete')?>"><i class="fa fa-trash-o"></i></a>
                                <a  data-toggle="tooltip" data-placement="top" data-original-title="<?= __('duplicate') ?>" class="btn btn-xs btn-default btn-equal" href="<?php echo $this->url('admin/default',array('controller'=>'certificate','action'=>'duplicate','id'=>$row->certificate_id));?>"  ><i class="fa fa-copy"></i></a>
                                <a  data-toggle="tooltip" data-placement="top" data-original-title="<?= __('student-downloads') ?>" class="btn btn-xs btn-default btn-equal" href="<?php echo $this->url('admin/default',array('controller'=>'certificate','action'=>'students','id'=>$row->certificate_id));?>"  ><i class="fa fa-users"></i></a>

                            </td>
                        </tr>
                    <?php endforeach; ?>

                    </tbody>
                </table>

                <?php
                // add at the end of the file after the table
                echo $this->paginationControl(
                // the paginator object
                    $this->paginator,
                    // the scrolling style
                    'sliding',
                    // the partial to use to render the control
                    array('partial/paginator.phtml', 'Admin'),
                    // the route to link to when a user clicks a control link
                    array(
                        'route' => 'admin/default',
                        'controller'=>'certificate',
                        'action'=>'index',
                    )
                );
                ?>
            </div><!--end .box-body -->
        </div><!--end .box -->
    </div><!--end .col-lg-12 -->
</div>


<!-- START SIMPLE MODAL MARKUP --><!-- /.modal -->
<!-- END SIMPLE MODAL MARKUP -->

 