   <?php if(isset($pageTitle))  $this->headTitle($pageTitle) ?>



            <!--breadcrumb-section ends-->
            <!--container starts-->
           <div class="container" style="background-color: white; min-height: 400px;   padding-bottom:50px; margin-bottom: 10px;    " >
           	<!--primary starts-->
            	 
           <div  style="padding-top: 20px">
               <?php echo $content; ?>
           </div>
          
            
           </div>
           
             <!--container ends-->
         