<div class="row">
    <div >
        <div class="box">

            <div class="box-body">
                <?php
                $form->prepare();
                $form->setAttribute('action', $this->url('admin/default',array('controller'=>'lesson','action'=>$action,'id'=>$id)));
                $form->setAttribute('method', 'post');
                $form->setAttribute('role', 'form');
                $form->setAttribute('class', 'form-horizontal');

                echo $this->form()->openTag($form);
                ?>




                <div class="form-group">
                    <?php     echo $this->formLabel($form->get('group_name'));

                    ?>
                    <?php     echo $this->formElement($form->get('group_name'));

                    ?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('group_name'));?></p>

                </div>




                <div class="form-group">
                    <?php     echo $this->formLabel($form->get('description'));

                    ?>
                    <?php     echo $this->formElement($form->get('description'));

                    ?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('description'));?></p>

                </div>



                <div class="form-group">
                    <?php     echo $this->formLabel($form->get('sort_order'));

                    ?>
                    <?php     echo $this->formElement($form->get('sort_order'));

                    ?>   <p class="help-block"><?php echo $this->formElementErrors($form->get('sort_order'));?></p>

                </div>






                <div class="form-footer">
                    <button type="submit" class="btn btn-primary"><?=__('save-changes')?></button>
                </div>
                <?php echo $this->form()->closeTag($form);  ?>
            </div>
        </div><!--end .box -->
    </div><!--end .col-lg-12 -->
</div>
