<div>
    <button onclick="image_upload()" id="addFileBtn" class="btn btn-primary"><i class="fa fa-plus"></i> <?= __('add-file') ?></button>
    <input id="file_name" type="hidden" name="file_name"/>
    <p><small><?= __('allowed-files') ?>: pdf, zip, mp4, mp3, doc, docx, ppt, pptx, xls, xlsx, png, jpeg, gif, txt, csv</small></p>
</div>
<div id="filelist">
<table class="table table-stripped">
    <thead>
    <tr>
        <th>
            <?= __('file') ?>
        </th>
        <th>
            <?= __('status') ?>
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($rowset as $row): ?>
    <tr>
        <td><strong><?php echo  $row->path; ?></strong></td>
        <td><?php echo (file_exists('public/usermedia/'.$row->path))? __('valid'):__('file_missing') ?></td>
        <td><a title="<?= __('delete') ?>" class="btn btn-primary delete" href="<?php echo $this->url('admin/default',['controller'=>'lesson','action'=>'removefile','id'=>$row->lesson_file_id]) ?>"><i class="fa fa-trash"></i></a>
            <a title="<?= __('download') ?>" class="btn btn-primary" href="<?php echo $this->url('admin/default',['controller'=>'lesson','action'=>'download','id'=>$row->lesson_file_id]) ?>"><i class="fa fa-download"></i></a>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>

</table>
</div>
<script type="text/javascript">


    function image_upload() {
        var field = 'file_name';
        $('#dialog').remove();

        $('#content').prepend('<div id="dialog" style="padding: 3px 0px 0px 0px;"><iframe src="<?php echo $this->basePath(); ?>/admin/filemanager?&token=true&field=' + encodeURIComponent(field) + '" style="padding:0; margin: 0; display: block; width: 100%; height: 100%;" frameborder="no" scrolling="auto"></iframe></div>');

        $('#dialog').dialog({
            title: '<?=__('Select A File')?>',
            close: function (event, ui) {

                if ($('#' + field).attr('value')) {
                    console.log($('#' + field).attr('value'));

                   $('#filelist').text('Loading...');
                    $.ajax({
                        url: '<?php echo $this->basePath(); ?>/admin/lesson/addfile/<?php echo $id ?>?&path=' + encodeURIComponent($('#' + field).val()),
                        dataType: 'text',
                        success: function(data) {
                            //$('#' + thumb).replaceWith('<img src="' + data + '" alt="" id="' + thumb + '" />');
                           // $('#layout_content').load('<?php echo $this->basePath(); ?>/admin/lesson/files/<?php echo $id ?>');
                            $('#layout_content').html(data);
                        }
                    });

                }

            },
            bgiframe: false,
            width: 800,
            height: 570,
            resizable: true,
            modal: false
        });
    };




    $(function(){
        $(document).on('click','.delete',function(e){
            e.preventDefault();
            $('#layout_content').text('<?=__('Loading')?>...');
            $('#layout_content').load($(this).attr('href'));
        });

        $(document).on('click','#genmodalinfo a',function(e){
            e.preventDefault();
            $('#genmodalinfo').text('<?=__('Loading')?>...');
            $('#genmodalinfo').load($(this).attr('href'));
        });



    })

</script>
