<form method="post" class="form" action="<?php echo $this->url('admin/default',['controller'=>'lecture','action'=>'editzoom','id'=>$id]) ?>">
  
    <div>

        <div class="form-group">
            <label for=""><?= __('title') ?></label>
            <input name="title" class="form-control"   required="required" value="<?=$data['title'] ?>" type="text">
        </div>
        <div class="form-group">
            <label for=""><?= __('meeting-id') ?></label>
            <input value="<?=$data['meeting_id']?>" required="required" class="form-control" type="text" name="meeting_id" placeholder="<?= __('zoom-placeholder') ?>"/>

        </div>


        <div class="form-group">
            <label for=""><?= __('meeting-password') ?></label>
            <input required="required" class="form-control" type="text" name="password" value="<?=$data['password']?>" />

        </div>

        <div class="form-group">
            <label for=""><?= __('instructions') ?> (<?= __('optional') ?>)</label>
            <textarea class="form-control" name="instructions"  ><?=$data['instructions']?></textarea>

        </div>


        <div class="form-group">
            <label for="sort_order"><?= __('sort-order') ?> (<?= __('optional') ?>)</label>
            <input name="sort_order"   class="form-control number" placeholder="<?= __('digits-only') ?>" value="<?=$data['sort_order'] ?>" type="text">   <p class="help-block"></p>

        </div>

    </div>
        <button type="submit" class="btn btn-primary"><?= __('save-changes') ?></button>

</form>
     