<?php $this->headScript()->prependFile($this->basePath() . '/static/loader/js/jquery.loadingModal.min.js')
?>
<?php echo $this->headLink()->prependStylesheet($this->basePath().'/static/loader/css/jquery.loadingModal.min.css');?>
<div class="row">

    <form id="importform" class="form" action="<?=selfURL()?>" method="post">

        <div class="form-group" style="padding-bottom: 20px">

            <div style="margin-bottom: 10px"><strong>Selected File:</strong> <span id="filename"></span> </div>
            <button type="button" onclick="image_upload()" id="addFileBtn" class="btn btn-primary"><i class="fa fa-plus"></i> Select Powerpoint File</button>
            <div>
                <?=$this->formElement($form->get('path'))?>
            </div>
        </div>

        <div class="form-group">
            <?=$this->formLabel($form->get('title'));?>
            <?=$this->formElement($form->get('title'));?>
        </div>


        <button class="btn btn-primary" type="submit">Import File</button>



    </form>


</div>

<script type="text/javascript">


    function image_upload() {
        var field = 'path';
        $('#dialog').remove();

        $('#content').prepend('<div id="dialog" style="padding: 3px 0px 0px 0px;"><iframe src="<?php echo $this->basePath(); ?>/admin/filemanager?&token=true&field=' + encodeURIComponent(field) + '" style="padding:0; margin: 0; display: block; width: 100%; height: 100%;" frameborder="no" scrolling="auto"></iframe></div>');

        $('#dialog').dialog({
            title: '<?=__('Select A File')?>',
            close: function (event, ui) {

                if ($('#' + field).attr('value')) {
                    console.log($('#' + field).attr('value'));
                    var fileName = $('#' + field).attr('value');
                    var file = fileName.substring(fileName.lastIndexOf('/')+1);
                    var extension = file.substring(file.lastIndexOf('.')+1);
                    extension = extension.toLowerCase();
                    if(extension=='ppt' || extension=='pptx'|| extension=='odp')
                    {
                        $('#filename').text(file);
                    }
                    else{
                        alert('Please select a Powerpoint/ODP file only');
                        $('#path').val('');
                        $('#filename').text('');
                    }





                }

            },
            bgiframe: false,
            width: 800,
            height: 570,
            resizable: true,
            modal: false
        });
    };


    $('#importform').submit(function(e){

        if($('#path').val()==''){
            e.preventDefault();
            alert('Please select a Powerpoint/ODP file to import');
        }
        else{
            $('body').loadingModal({
                text: 'Importing File. Please wait...'
            })
        }
    });

</script>

